import type { Response as ExpressResponse } from 'express';
import { CredentialService, BulkCredentialResult } from './credential.service';
import { Role } from '../auth/types/role.enum';
import { PrismaService } from '../prisma/prisma.service';
export interface BulkStudentCreationDto {
    students: Array<{
        name: string;
        email?: string;
        gender?: string;
        phone?: string;
        address?: string;
    }>;
    academicYear: string;
    grade: number;
    className?: string;
    section?: string;
}
export interface GenerateCredentialsDto {
    count: number;
    academicYear: string;
    role: Role;
}
export interface CreateStaffDto {
    staff: Array<{
        name: string;
        email: string;
        role: Role.TEACHER | Role.ADMIN | Role.IT_MANAGER | Role.REGISTRAR | Role.FINANCE;
        phone?: string;
        generateCredentials?: boolean;
        username?: string;
        password?: string;
    }>;
    academicYear?: string;
}
export declare class CredentialController {
    private readonly credentialService;
    private readonly prismaService;
    constructor(credentialService: CredentialService, prismaService: PrismaService);
    private resolveSchoolScope;
    private createStaffUserRecord;
    previewStudentId(req: any, schoolId: string, academicYear: string): Promise<{
        schoolName: string;
        schoolCode: string | null;
        academicYear: string;
        currentCount: number;
        nextAdmissionNumber: string | null;
        message: string;
    }>;
    previewStaffId(req: any, schoolId: string, role: Role, academicYear?: string): Promise<{
        schoolName: string;
        schoolCode: string | null;
        role: Role.ADMIN | Role.IT_MANAGER | Role.TEACHER | Role.PARENT;
        year: string;
        currentCount: number;
        nextStaffId: string | null;
        message: string;
    }>;
    generateBulkCredentials(dto: GenerateCredentialsDto, req: any): Promise<{
        message: string;
        credentials: {
            username: string;
            temporaryPassword: string;
            hashedPassword: string;
            role: Role;
        }[];
    }>;
    bulkCreateStudents(dto: BulkStudentCreationDto, req: any): Promise<{
        message: string;
        students: {
            id: string;
            name: string;
            email?: string | null;
            username: string;
            temporaryPassword: string;
            role: Role;
        }[];
        credentials: {
            name: string;
            email: string | null | undefined;
            username: string;
            temporaryPassword: string;
            role: Role;
        }[];
        note: string;
    }>;
    bulkCreateStaff(dto: {
        staff: Array<{
            name: string;
            email: string;
            role: Role.TEACHER | Role.ADMIN | Role.IT_MANAGER | Role.REGISTRAR | Role.FINANCE;
            phone?: string;
        }>;
        academicYear?: string;
    }, req: any): Promise<{
        message: string;
        staff: {
            id: string;
            name: string;
            email: string;
            username: string;
            temporaryPassword: string;
            role: Role;
        }[];
        credentials: {
            name: string;
            email: string;
            username: string;
            temporaryPassword: string;
            role: Role;
        }[];
        note: string;
    }>;
    createStaff(dto: CreateStaffDto, req: any): Promise<{
        message: string;
        staff: {
            id: string;
            name: string;
            email: string;
            username: string;
            temporaryPassword: string;
            role: Role;
            wasAutoGenerated: boolean;
        }[];
        credentials: {
            name: string;
            email: string;
            username: string;
            temporaryPassword: string;
            role: Role;
            wasAutoGenerated: boolean;
        }[];
        note: string;
    }>;
    createStudents(dto: {
        students: Array<{
            name: string;
            email?: string;
            phone?: string;
            motherName?: string;
            motherPhone?: string;
            parentName?: string;
            parentPhone?: string;
            relation?: string;
            parentEmail?: string;
            faydaNumber?: string;
            gender?: string;
            stream?: string | null;
            generateCredentials?: boolean;
            username?: string;
            password?: string;
            classId?: string;
            sectionId?: string;
        }>;
        academicYear?: string;
    }, req: any): Promise<{
        message: string;
        students: {
            id: string;
            name: string;
            email?: string | null;
            username: string;
            temporaryPassword: string;
            role: Role;
            wasAutoGenerated: boolean;
        }[];
        credentials: {
            name: string;
            email: string | null | undefined;
            username: string;
            temporaryPassword: string;
            role: Role;
            wasAutoGenerated: boolean;
        }[];
        note: string;
    }>;
    exportCredentialsToCSV(credentials: BulkCredentialResult[], res: ExpressResponse): Promise<void>;
    generateCredentialSlips(credentials: BulkCredentialResult[], req: any): Promise<{
        slips: import("./credential.service").CredentialSlip[];
        printableFormat: {
            title: string;
            header: string;
            body: string;
        }[];
    }>;
    validatePassword(password: string): Promise<{
        isValid: boolean;
        errors: string[];
    }>;
    checkUsername(username: string, req: any): Promise<{
        username: string;
        isUnique: boolean;
        message: string;
    }>;
    listCredentials(req: any, status?: 'pending' | 'sent' | 'all', role?: string, search?: string, page?: string, limit?: string): Promise<{
        data: ({
            user: {
                id: string;
                isActive: boolean;
            } | null;
        } & {
            id: string;
            name: string;
            role: string;
            email: string | null;
            username: string;
            schoolId: string;
            createdAt: Date;
            temporaryPassword: string;
            userId: string | null;
            expiresAt: Date;
            isSent: boolean;
            sentAt: Date | null;
            sentVia: string | null;
            batchId: string | null;
        })[];
        meta: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    getCredentialStats(req: any): Promise<{
        total: number;
        pending: number;
        sent: number;
        byRole: {
            role: string;
            count: number;
        }[];
    }>;
    sendBulkCredentials(req: any): Promise<{
        message: string;
        count: number;
    }>;
    markAsSent(id: string, sentVia: string | undefined, req: any): Promise<{
        id: string;
        name: string;
        role: string;
        email: string | null;
        username: string;
        schoolId: string;
        createdAt: Date;
        temporaryPassword: string;
        userId: string | null;
        expiresAt: Date;
        isSent: boolean;
        sentAt: Date | null;
        sentVia: string | null;
        batchId: string | null;
    }>;
    deleteCredential(id: string, req: any): Promise<{
        success: boolean;
        message: string;
    }>;
    assignRollNumbersByAlphabet(req: any, body: {
        academicYearId: string;
    }): Promise<{
        updated: number;
        success: boolean;
    }>;
    private extractYearFromAcademicYear;
}
