"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DEFAULT_LANGUAGE = exports.SUPPORTED_LANGUAGES = exports.LANGUAGE_OPTIONS = exports.SupportedLocales = exports.SetLocale = exports.Locale = exports.LocaleMiddleware = exports.LocalizationInterceptor = exports.LocalizedExceptionFilter = exports.LocalizedException = exports.FallbackManager = exports.InMemoryTranslationCache = exports.FileTranslationLoader = exports.TemplateRenderer = exports.PluralizationService = exports.NumberFormatter = exports.DateFormatter = exports.MessageFormatter = exports.TranslationService = exports.LocaleResolver = exports.LocalizationModule = void 0;
var localization_module_1 = require("./localization.module");
Object.defineProperty(exports, "LocalizationModule", { enumerable: true, get: function () { return localization_module_1.LocalizationModule; } });
var locale_resolver_service_1 = require("./services/locale-resolver.service");
Object.defineProperty(exports, "LocaleResolver", { enumerable: true, get: function () { return locale_resolver_service_1.LocaleResolver; } });
var translation_service_1 = require("./services/translation.service");
Object.defineProperty(exports, "TranslationService", { enumerable: true, get: function () { return translation_service_1.TranslationService; } });
var message_formatter_service_1 = require("./services/message-formatter.service");
Object.defineProperty(exports, "MessageFormatter", { enumerable: true, get: function () { return message_formatter_service_1.MessageFormatter; } });
var date_formatter_service_1 = require("./services/date-formatter.service");
Object.defineProperty(exports, "DateFormatter", { enumerable: true, get: function () { return date_formatter_service_1.DateFormatter; } });
var number_formatter_service_1 = require("./services/number-formatter.service");
Object.defineProperty(exports, "NumberFormatter", { enumerable: true, get: function () { return number_formatter_service_1.NumberFormatter; } });
var pluralization_service_1 = require("./services/pluralization.service");
Object.defineProperty(exports, "PluralizationService", { enumerable: true, get: function () { return pluralization_service_1.PluralizationService; } });
var template_renderer_service_1 = require("./services/template-renderer.service");
Object.defineProperty(exports, "TemplateRenderer", { enumerable: true, get: function () { return template_renderer_service_1.TemplateRenderer; } });
var file_loader_service_1 = require("./loaders/file-loader.service");
Object.defineProperty(exports, "FileTranslationLoader", { enumerable: true, get: function () { return file_loader_service_1.FileTranslationLoader; } });
var translation_cache_service_1 = require("./cache/translation-cache.service");
Object.defineProperty(exports, "InMemoryTranslationCache", { enumerable: true, get: function () { return translation_cache_service_1.InMemoryTranslationCache; } });
var fallback_manager_service_1 = require("./fallback/fallback-manager.service");
Object.defineProperty(exports, "FallbackManager", { enumerable: true, get: function () { return fallback_manager_service_1.FallbackManager; } });
var localized_exception_1 = require("./exceptions/localized-exception");
Object.defineProperty(exports, "LocalizedException", { enumerable: true, get: function () { return localized_exception_1.LocalizedException; } });
var localized_exception_filter_1 = require("./filters/localized-exception.filter");
Object.defineProperty(exports, "LocalizedExceptionFilter", { enumerable: true, get: function () { return localized_exception_filter_1.LocalizedExceptionFilter; } });
var localization_interceptor_1 = require("./interceptors/localization.interceptor");
Object.defineProperty(exports, "LocalizationInterceptor", { enumerable: true, get: function () { return localization_interceptor_1.LocalizationInterceptor; } });
var locale_middleware_1 = require("./middleware/locale.middleware");
Object.defineProperty(exports, "LocaleMiddleware", { enumerable: true, get: function () { return locale_middleware_1.LocaleMiddleware; } });
var locale_decorator_1 = require("./decorators/locale.decorator");
Object.defineProperty(exports, "Locale", { enumerable: true, get: function () { return locale_decorator_1.Locale; } });
Object.defineProperty(exports, "SetLocale", { enumerable: true, get: function () { return locale_decorator_1.SetLocale; } });
Object.defineProperty(exports, "SupportedLocales", { enumerable: true, get: function () { return locale_decorator_1.SupportedLocales; } });
var localization_interface_1 = require("./interfaces/localization.interface");
Object.defineProperty(exports, "LANGUAGE_OPTIONS", { enumerable: true, get: function () { return localization_interface_1.LANGUAGE_OPTIONS; } });
Object.defineProperty(exports, "SUPPORTED_LANGUAGES", { enumerable: true, get: function () { return localization_interface_1.SUPPORTED_LANGUAGES; } });
Object.defineProperty(exports, "DEFAULT_LANGUAGE", { enumerable: true, get: function () { return localization_interface_1.DEFAULT_LANGUAGE; } });
//# sourceMappingURL=index.js.map