import api from "./core";

export const rolesAPI = {
  getAll: () => api.get("/roles"),
  getPermissions: (role: string) => api.get(`/roles/${role}/permissions`),
  assignPermission: (role: string, permissionId: string) =>
    api.post(`/roles/${role}/permissions`, { permissionId }),
  removePermission: (role: string, permissionId: string) =>
    api.delete(`/roles/${role}/permissions/${permissionId}`),
};

export const permissionsAPI = {
  create: (data: { name: string; description: string; module: string; action: string }) =>
    api.post("/permissions", data),
  getAll: () => api.get("/permissions"),
  getById: (id: string) => api.get(`/permissions/${id}`),
  getByModule: (module: string) => api.get(`/permissions/module/${module}`),
  update: (
    id: string,
    data: { name?: string; description?: string; module?: string; action?: string }
  ) => api.put(`/permissions/${id}`, data),
  delete: (id: string) => api.delete(`/permissions/${id}`),
};

export const autoAssignmentAPI = {
  autoAssign: (enrollmentId: string) =>
    api.post(`/auto-assignment/enrollments/${enrollmentId}/auto-assign`),
  bulkAutoAssign: (enrollmentIds: string[]) =>
    api.post("/auto-assignment/bulk", { enrollmentIds }),
  reassign: (enrollmentId: string) =>
    api.post(`/auto-assignment/enrollments/${enrollmentId}/reassign`),
  getStudentAssignment: (studentId: string) =>
    api.get(`/auto-assignment/students/${studentId}/assignment`),
  getCapacity: (academicYear: string, grade: string) =>
    api.get("/auto-assignment/capacity", { params: { academicYear, grade } }),
  approveAndAssign: (enrollmentId: string) =>
    api.post("/auto-assignment/approve-and-assign", { enrollmentId }),
};

export interface BulkStudentCreationDto {
  students: Array<{
    name: string;
    email: string;
    gender?: string;
    phone?: string;
    address?: string;
  }>;
  academicYear: string;
  grade: number;
  className?: string;
  section?: string;
}

export interface CredentialResult {
  name: string;
  email: string;
  username: string;
  temporaryPassword: string;
  role: string;
}

export interface StudentIdPreview {
  schoolName: string;
  schoolCode: string;
  academicYear: string;
  currentCount: number;
  nextAdmissionNumber: string | null;
  message: string;
}

export interface StaffIdPreview {
  schoolName: string;
  schoolCode: string;
  role: string;
  year: string;
  currentCount: number;
  nextStaffId: string | null;
  message: string;
}

export interface CredentialSlip {
  schoolLogo?: string;
  schoolName: string;
  schoolCode: string;
  studentName: string;
  admissionNumber: string;
  username: string;
  temporaryPassword: string;
  instructions: string[];
  generatedAt: Date;
}

export interface PendingCredential {
  id: string;
  schoolId: string;
  userId: string | null;
  name: string;
  email: string | null;
  username: string;
  temporaryPassword: string;
  role: string;
  isSent: boolean;
  sentAt: string | null;
  sentVia: string | null;
  createdAt: string;
  expiresAt: string;
}

export interface CredentialStats {
  total: number;
  pending: number;
  sent: number;
  byRole: { role: string; count: number }[];
}

export const credentialsAPI = {
  previewStudentId: (schoolId: string, academicYear: string) =>
    api.get<StudentIdPreview>(`/credentials/preview/student/${schoolId}`, {
      params: { academicYear },
    }),
  previewStaffId: (schoolId: string, role: string, academicYear?: string) =>
    api.get<StaffIdPreview>(`/credentials/preview/staff/${schoolId}`, {
      params: { role, academicYear },
    }),
  generateBulkCredentials: (data: { count: number; academicYear: string; role: string }) =>
    api.post("/credentials/generate/bulk", data),
  bulkCreateStudents: (data: BulkStudentCreationDto) =>
    api.post<{ message: string; students: CredentialResult[]; credentials: CredentialResult[]; note: string }>(
      "/credentials/students/bulk",
      data
    ),
  bulkCreateStaff: (data: {
    staff: Array<{
      name: string;
      email: string;
      role: "TEACHER" | "ADMIN" | "IT_MANAGER" | "PARENT";
      phone?: string;
    }>;
    academicYear?: string;
  }) =>
    api.post<{ message: string; staff: CredentialResult[]; credentials: CredentialResult[]; note: string }>(
      "/credentials/staff/bulk",
      data
    ),
  createStaff: (data: {
    staff: Array<{
      name: string;
      email: string;
      role: "TEACHER" | "ADMIN" | "IT_MANAGER" | "PARENT" | "REGISTRAR" | "FINANCE";
      phone?: string;
      generateCredentials?: boolean;
      username?: string;
      password?: string;
    }>;
    academicYear?: string;
  }) =>
    api.post<{
      message: string;
      staff: Array<CredentialResult & { wasAutoGenerated: boolean }>;
      credentials: Array<CredentialResult & { wasAutoGenerated: boolean }>;
      note: string;
    }>("/credentials/staff/create", data),
  createStudent: (data: {
    students: Array<{
      name: string;
      email?: string;
      phone?: string;
      parentEmail?: string;
      gender?: string;
      generateCredentials?: boolean;
      username?: string;
      password?: string;
      classId?: string;
      sectionId?: string;
      promoteToNextClass?: boolean;
    }>;
    academicYear?: string;
  }) =>
    api.post<{
      message: string;
      students: Array<CredentialResult & { wasAutoGenerated: boolean }>;
      credentials: Array<CredentialResult & { wasAutoGenerated: boolean }>;
      note: string;
    }>("/credentials/students/create", data),
  exportToCSV: (credentials: CredentialResult[]) =>
    api.post("/credentials/export/csv", credentials, { responseType: "blob" }),
  generateSlips: (credentials: CredentialResult[]) =>
    api.post<{ slips: CredentialSlip[]; printableFormat: any[] }>("/credentials/slips", credentials),
  validatePassword: (password: string) => api.post("/credentials/validate-password", { password }),
  checkUsername: (username: string) =>
    api.get<{ username: string; isUnique: boolean; message: string }>(
      `/credentials/check-username/${username}`
    ),
  list: (params: {
    status?: "pending" | "sent" | "all";
    role?: string;
    search?: string;
    page?: number;
    limit?: number;
  }) => api.get("/credentials", { params }),
  getStats: () => api.get("/credentials/stats"),
  markAsSent: (id: string, sentVia?: string) => api.post(`/credentials/${id}/send`, { sentVia }),
  delete: (id: string) => api.delete(`/credentials/${id}`),
};

export const classSubjectsAPI = {
  create: (data: {
    classId: string;
    sectionId: string;
    subjectId: string;
    academicYearId: string;
    teacherId?: string;
  }) => api.post("/class-subjects", data),
  getAll: (params?: { schoolId?: string; academicYearId?: string }) =>
    api.get("/class-subjects", { params }),
  getByClass: (classId: string, sectionId?: string) =>
    api.get(`/class-subjects/by-class/${classId}`, { params: { sectionId } }),
  getByTeacher: (teacherId: string, params?: { academicYearId?: string }) =>
    api.get(`/class-subjects/by-teacher/${teacherId}`, { params }),
  getById: (id: string) => api.get(`/class-subjects/${id}`),
  update: (id: string, data: { teacherId?: string }) => api.put(`/class-subjects/${id}`, data),
  delete: (id: string) => api.delete(`/class-subjects/${id}`),
  getMatrix: (params: { schoolId: string; academicYearId: string }) =>
    api.get("/class-subjects/matrix", { params }),
  bulkAssign: (data: any) => api.post("/class-subjects/bulk-assign", data),
};

export const dashboardAPI = {
  getDashboard: () => api.get("/dashboard"),
  getTeacherDashboard: () => api.get("/dashboard/teacher"),
  getStudentDashboard: () => api.get("/dashboard/student"),
  getParentDashboard: () => api.get("/dashboard/parent"),
  getAdminDashboard: () => api.get("/dashboard/admin"),
  getItManagerDashboard: () => api.get("/dashboard/it-manager"),
  getRegistrarDashboard: () => api.get("/dashboard/registrar"),
  getSuperadminDashboard: () => api.get("/dashboard/superadmin"),
};
