import { PracticeExamsService } from './practice-exams.service';
export declare class PracticeExamsController {
    private readonly service;
    constructor(service: PracticeExamsService);
    listAdmin(req: any, query: any): Promise<({
        _count: {
            attempts: number;
            questions: number;
        };
        subject: {
            id: string;
            name: string;
            code: string | null;
        } | null;
    } & {
        id: string;
        description: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        grade: number;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        stream: string | null;
        status: import("@prisma/client").$Enums.PracticeExamStatus;
        title: string;
        subjectId: string | null;
        passMark: number;
        createdById: string | null;
        accessCode: string;
        durationMinutes: number;
        shuffleQuestions: boolean;
    })[]>;
    listTeacherSubmissions(req: any, query: any): Promise<{
        exam: {
            questions: undefined;
            class: any;
            section: any;
            _count: {
                questions: number;
            };
            subject: {
                id: string;
                name: string;
                code: string | null;
            } | null;
            id: string;
            description: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            grade: number;
            classId: string | null;
            sectionId: string | null;
            academicYearId: string | null;
            stream: string | null;
            status: import("@prisma/client").$Enums.PracticeExamStatus;
            title: string;
            subjectId: string | null;
            passMark: number;
            createdById: string | null;
            accessCode: string;
            durationMinutes: number;
            shuffleQuestions: boolean;
        };
        student: {
            studentClasses: undefined;
            id: string;
            name: string;
            username: string | null;
            studentProfile: {
                section: string | null;
                stream: string | null;
                studentCode: string;
                className: string | null;
                rollNumber: string | null;
            } | null;
        };
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date;
        studentId: string;
        status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
        submittedAt: Date | null;
        percentage: number | null;
        score: number | null;
        skippedCount: number;
        examId: string;
        startedAt: Date;
        correctCount: number;
        wrongCount: number;
    }[]>;
    createExam(req: any, body: any): Promise<{
        id: string;
        description: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        grade: number;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        stream: string | null;
        status: import("@prisma/client").$Enums.PracticeExamStatus;
        title: string;
        subjectId: string | null;
        passMark: number;
        createdById: string | null;
        accessCode: string;
        durationMinutes: number;
        shuffleQuestions: boolean;
    }>;
    getExam(req: any, examId: string): Promise<({
        [x: string]: ({
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            expiresAt: Date;
            studentId: string;
            status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
            submittedAt: Date | null;
            percentage: number | null;
            score: number | null;
            skippedCount: number;
            examId: string;
            startedAt: Date;
            correctCount: number;
            wrongCount: number;
        } | {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            expiresAt: Date;
            studentId: string;
            status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
            submittedAt: Date | null;
            percentage: number | null;
            score: number | null;
            skippedCount: number;
            examId: string;
            startedAt: Date;
            correctCount: number;
            wrongCount: number;
        })[] | ({
            id: string;
            isActive: boolean;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            subject: string;
            order: number;
            examId: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            questionText: string;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            correctText: string | null;
            caseSensitive: boolean;
        } | {
            id: string;
            isActive: boolean;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            subject: string;
            order: number;
            examId: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            questionText: string;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            correctText: string | null;
            caseSensitive: boolean;
        })[] | {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            expiresAt: Date;
            studentId: string;
            status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
            submittedAt: Date | null;
            percentage: number | null;
            score: number | null;
            skippedCount: number;
            examId: string;
            startedAt: Date;
            correctCount: number;
            wrongCount: number;
        }[] | {
            id: string;
            isActive: boolean;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            subject: string;
            order: number;
            examId: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            questionText: string;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            correctText: string | null;
            caseSensitive: boolean;
        }[];
        [x: number]: never;
        [x: symbol]: never;
    } & {
        id: string;
        description: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        grade: number;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        stream: string | null;
        status: import("@prisma/client").$Enums.PracticeExamStatus;
        title: string;
        subjectId: string | null;
        passMark: number;
        createdById: string | null;
        accessCode: string;
        durationMinutes: number;
        shuffleQuestions: boolean;
    }) | null>;
    updateExam(req: any, examId: string, body: any): Promise<{
        id: string;
        description: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        grade: number;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        stream: string | null;
        status: import("@prisma/client").$Enums.PracticeExamStatus;
        title: string;
        subjectId: string | null;
        passMark: number;
        createdById: string | null;
        accessCode: string;
        durationMinutes: number;
        shuffleQuestions: boolean;
    }>;
    deleteExam(req: any, examId: string): Promise<{
        message: string;
    }>;
    addQuestion(req: any, examId: string, body: any): Promise<{
        id: string;
        isActive: boolean;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        subject: string;
        order: number;
        examId: string;
        questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
        questionText: string;
        optionA: string | null;
        optionB: string | null;
        optionC: string | null;
        optionD: string | null;
        correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
        correctText: string | null;
        caseSensitive: boolean;
    }>;
    importQuestions(req: any, examId: string, body: {
        csv: string;
    }): Promise<{
        createdCount: number;
        failedCount: number;
        failed: any[];
    }>;
    updateQuestion(req: any, examId: string, questionId: string, body: any): Promise<{
        id: string;
        isActive: boolean;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        subject: string;
        order: number;
        examId: string;
        questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
        questionText: string;
        optionA: string | null;
        optionB: string | null;
        optionC: string | null;
        optionD: string | null;
        correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
        correctText: string | null;
        caseSensitive: boolean;
    }>;
    deleteQuestion(req: any, examId: string, questionId: string): Promise<{
        message: string;
    }>;
    getResults(req: any, examId: string): Promise<({
        student: {
            id: string;
            name: string;
            username: string | null;
        };
    } & {
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date;
        studentId: string;
        status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
        submittedAt: Date | null;
        percentage: number | null;
        score: number | null;
        skippedCount: number;
        examId: string;
        startedAt: Date;
        correctCount: number;
        wrongCount: number;
    })[]>;
    listAvailable(req: any): Promise<{
        id: string;
        description: string | null;
        _count: {
            questions: number;
        };
        subject: {
            id: string;
            name: string;
            code: string | null;
        } | null;
        grade: number;
        classId: string | null;
        sectionId: string | null;
        stream: string | null;
        status: import("@prisma/client").$Enums.PracticeExamStatus;
        title: string;
        subjectId: string | null;
        passMark: number;
        createdById: string | null;
        attempts: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            expiresAt: Date;
            studentId: string;
            status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
            submittedAt: Date | null;
            percentage: number | null;
            score: number | null;
            skippedCount: number;
            examId: string;
            startedAt: Date;
            correctCount: number;
            wrongCount: number;
        }[];
        durationMinutes: number;
        shuffleQuestions: boolean;
    }[]>;
    startAttempt(req: any, examId: string, body: any): Promise<{
        questions: {
            correctOption?: import("@prisma/client").$Enums.PracticeExamOption | null | undefined;
            isCorrect?: boolean | null | undefined;
            id: string;
            subject: string;
            questionText: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctText: string | null | undefined;
            caseSensitive: boolean;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
        }[];
        exam?: ({
            subject: {
                id: string;
                name: string;
                code: string | null;
            } | null;
            questions: {
                id: string;
                isActive: boolean;
                schoolId: string;
                createdAt: Date;
                updatedAt: Date;
                subject: string;
                order: number;
                examId: string;
                questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
                questionText: string;
                optionA: string | null;
                optionB: string | null;
                optionC: string | null;
                optionD: string | null;
                correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
                correctText: string | null;
                caseSensitive: boolean;
            }[];
        } & {
            id: string;
            description: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            grade: number;
            classId: string | null;
            sectionId: string | null;
            academicYearId: string | null;
            stream: string | null;
            status: import("@prisma/client").$Enums.PracticeExamStatus;
            title: string;
            subjectId: string | null;
            passMark: number;
            createdById: string | null;
            accessCode: string;
            durationMinutes: number;
            shuffleQuestions: boolean;
        }) | undefined;
        answers?: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            studentId: string;
            examId: string;
            attemptId: string;
            questionId: string;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
            isCorrect: boolean | null;
        }[] | undefined;
        id?: string | undefined;
        schoolId?: string | undefined;
        createdAt?: Date | undefined;
        updatedAt?: Date | undefined;
        expiresAt?: Date | undefined;
        studentId?: string | undefined;
        status?: import("@prisma/client").$Enums.PracticeExamAttemptStatus | undefined;
        submittedAt?: Date | null | undefined;
        percentage?: number | null | undefined;
        score?: number | null | undefined;
        skippedCount?: number | undefined;
        examId?: string | undefined;
        startedAt?: Date | undefined;
        correctCount?: number | undefined;
        wrongCount?: number | undefined;
    }>;
    getAttempt(req: any, attemptId: string): Promise<{
        questions: {
            correctOption?: import("@prisma/client").$Enums.PracticeExamOption | null | undefined;
            isCorrect?: boolean | null | undefined;
            id: string;
            subject: string;
            questionText: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctText: string | null | undefined;
            caseSensitive: boolean;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
        }[];
        exam?: ({
            subject: {
                id: string;
                name: string;
                code: string | null;
            } | null;
            questions: {
                id: string;
                isActive: boolean;
                schoolId: string;
                createdAt: Date;
                updatedAt: Date;
                subject: string;
                order: number;
                examId: string;
                questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
                questionText: string;
                optionA: string | null;
                optionB: string | null;
                optionC: string | null;
                optionD: string | null;
                correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
                correctText: string | null;
                caseSensitive: boolean;
            }[];
        } & {
            id: string;
            description: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            grade: number;
            classId: string | null;
            sectionId: string | null;
            academicYearId: string | null;
            stream: string | null;
            status: import("@prisma/client").$Enums.PracticeExamStatus;
            title: string;
            subjectId: string | null;
            passMark: number;
            createdById: string | null;
            accessCode: string;
            durationMinutes: number;
            shuffleQuestions: boolean;
        }) | undefined;
        answers?: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            studentId: string;
            examId: string;
            attemptId: string;
            questionId: string;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
            isCorrect: boolean | null;
        }[] | undefined;
        id?: string | undefined;
        schoolId?: string | undefined;
        createdAt?: Date | undefined;
        updatedAt?: Date | undefined;
        expiresAt?: Date | undefined;
        studentId?: string | undefined;
        status?: import("@prisma/client").$Enums.PracticeExamAttemptStatus | undefined;
        submittedAt?: Date | null | undefined;
        percentage?: number | null | undefined;
        score?: number | null | undefined;
        skippedCount?: number | undefined;
        examId?: string | undefined;
        startedAt?: Date | undefined;
        correctCount?: number | undefined;
        wrongCount?: number | undefined;
    }>;
    autosave(req: any, attemptId: string, body: any): Promise<{
        message: string;
        savedCount: number;
    }>;
    submit(req: any, attemptId: string, body: any): Promise<{
        questions: {
            correctOption?: import("@prisma/client").$Enums.PracticeExamOption | null | undefined;
            isCorrect?: boolean | null | undefined;
            id: string;
            subject: string;
            questionText: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctText: string | null | undefined;
            caseSensitive: boolean;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
        }[];
        exam?: ({
            subject: {
                id: string;
                name: string;
                code: string | null;
            } | null;
            questions: {
                id: string;
                isActive: boolean;
                schoolId: string;
                createdAt: Date;
                updatedAt: Date;
                subject: string;
                order: number;
                examId: string;
                questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
                questionText: string;
                optionA: string | null;
                optionB: string | null;
                optionC: string | null;
                optionD: string | null;
                correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
                correctText: string | null;
                caseSensitive: boolean;
            }[];
        } & {
            id: string;
            description: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            grade: number;
            classId: string | null;
            sectionId: string | null;
            academicYearId: string | null;
            stream: string | null;
            status: import("@prisma/client").$Enums.PracticeExamStatus;
            title: string;
            subjectId: string | null;
            passMark: number;
            createdById: string | null;
            accessCode: string;
            durationMinutes: number;
            shuffleQuestions: boolean;
        }) | undefined;
        answers?: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            studentId: string;
            examId: string;
            attemptId: string;
            questionId: string;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
            isCorrect: boolean | null;
        }[] | undefined;
        id?: string | undefined;
        schoolId?: string | undefined;
        createdAt?: Date | undefined;
        updatedAt?: Date | undefined;
        expiresAt?: Date | undefined;
        studentId?: string | undefined;
        status?: import("@prisma/client").$Enums.PracticeExamAttemptStatus | undefined;
        submittedAt?: Date | null | undefined;
        percentage?: number | null | undefined;
        score?: number | null | undefined;
        skippedCount?: number | undefined;
        examId?: string | undefined;
        startedAt?: Date | undefined;
        correctCount?: number | undefined;
        wrongCount?: number | undefined;
    }>;
}
