import { PracticeExamOption } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
type AnswerInput = {
    questionId: string;
    selectedOption?: PracticeExamOption | null;
    textAnswer?: string | null;
    isFlagged?: boolean;
};
export declare class PracticeExamsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    private normalizeGrade;
    private assertGradeAllowedForSchool;
    private normalizeStream;
    private normalizeStatus;
    private normalizeAccessCode;
    private generateAccessCode;
    private isAdminRole;
    private assertTeacherAssignment;
    private assertCanManageExam;
    private assertExamCanBeActivated;
    private assertQuestionBankEditable;
    private normalizeOption;
    private normalizeQuestionType;
    private normalizeTextAnswer;
    private isTextAnswerCorrect;
    private isAnswerCorrect;
    private isAnswerProvided;
    private ensureQuestionPayload;
    listAdmin(schoolId: string, query: any, userId?: string, role?: string): Promise<({
        _count: {
            attempts: number;
            questions: number;
        };
        subject: {
            id: string;
            name: string;
            code: string | null;
        } | null;
    } & {
        id: string;
        description: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        grade: number;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        stream: string | null;
        status: import("@prisma/client").$Enums.PracticeExamStatus;
        title: string;
        subjectId: string | null;
        passMark: number;
        createdById: string | null;
        accessCode: string;
        durationMinutes: number;
        shuffleQuestions: boolean;
    })[]>;
    listTeacherSubmissions(schoolId: string, userId: string, role?: string, query?: any): Promise<{
        exam: {
            questions: undefined;
            class: any;
            section: any;
            _count: {
                questions: number;
            };
            subject: {
                id: string;
                name: string;
                code: string | null;
            } | null;
            id: string;
            description: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            grade: number;
            classId: string | null;
            sectionId: string | null;
            academicYearId: string | null;
            stream: string | null;
            status: import("@prisma/client").$Enums.PracticeExamStatus;
            title: string;
            subjectId: string | null;
            passMark: number;
            createdById: string | null;
            accessCode: string;
            durationMinutes: number;
            shuffleQuestions: boolean;
        };
        student: {
            studentClasses: undefined;
            id: string;
            name: string;
            username: string | null;
            studentProfile: {
                section: string | null;
                stream: string | null;
                studentCode: string;
                className: string | null;
                rollNumber: string | null;
            } | null;
        };
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date;
        studentId: string;
        status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
        submittedAt: Date | null;
        percentage: number | null;
        score: number | null;
        skippedCount: number;
        examId: string;
        startedAt: Date;
        correctCount: number;
        wrongCount: number;
    }[]>;
    createExam(schoolId: string, createdById: string, body: any, role?: string): Promise<{
        id: string;
        description: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        grade: number;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        stream: string | null;
        status: import("@prisma/client").$Enums.PracticeExamStatus;
        title: string;
        subjectId: string | null;
        passMark: number;
        createdById: string | null;
        accessCode: string;
        durationMinutes: number;
        shuffleQuestions: boolean;
    }>;
    getAdminExam(schoolId: string, examId: string, userId?: string, role?: string): Promise<({
        [x: string]: ({
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            expiresAt: Date;
            studentId: string;
            status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
            submittedAt: Date | null;
            percentage: number | null;
            score: number | null;
            skippedCount: number;
            examId: string;
            startedAt: Date;
            correctCount: number;
            wrongCount: number;
        } | {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            expiresAt: Date;
            studentId: string;
            status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
            submittedAt: Date | null;
            percentage: number | null;
            score: number | null;
            skippedCount: number;
            examId: string;
            startedAt: Date;
            correctCount: number;
            wrongCount: number;
        })[] | ({
            id: string;
            isActive: boolean;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            subject: string;
            order: number;
            examId: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            questionText: string;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            correctText: string | null;
            caseSensitive: boolean;
        } | {
            id: string;
            isActive: boolean;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            subject: string;
            order: number;
            examId: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            questionText: string;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            correctText: string | null;
            caseSensitive: boolean;
        })[] | {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            expiresAt: Date;
            studentId: string;
            status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
            submittedAt: Date | null;
            percentage: number | null;
            score: number | null;
            skippedCount: number;
            examId: string;
            startedAt: Date;
            correctCount: number;
            wrongCount: number;
        }[] | {
            id: string;
            isActive: boolean;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            subject: string;
            order: number;
            examId: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            questionText: string;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            correctText: string | null;
            caseSensitive: boolean;
        }[];
        [x: number]: never;
        [x: symbol]: never;
    } & {
        id: string;
        description: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        grade: number;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        stream: string | null;
        status: import("@prisma/client").$Enums.PracticeExamStatus;
        title: string;
        subjectId: string | null;
        passMark: number;
        createdById: string | null;
        accessCode: string;
        durationMinutes: number;
        shuffleQuestions: boolean;
    }) | null>;
    updateExam(schoolId: string, examId: string, body: any, userId?: string, role?: string): Promise<{
        id: string;
        description: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        grade: number;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        stream: string | null;
        status: import("@prisma/client").$Enums.PracticeExamStatus;
        title: string;
        subjectId: string | null;
        passMark: number;
        createdById: string | null;
        accessCode: string;
        durationMinutes: number;
        shuffleQuestions: boolean;
    }>;
    deleteExam(schoolId: string, examId: string, userId?: string, role?: string): Promise<{
        message: string;
    }>;
    addQuestion(schoolId: string, examId: string, body: any, userId?: string, role?: string): Promise<{
        id: string;
        isActive: boolean;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        subject: string;
        order: number;
        examId: string;
        questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
        questionText: string;
        optionA: string | null;
        optionB: string | null;
        optionC: string | null;
        optionD: string | null;
        correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
        correctText: string | null;
        caseSensitive: boolean;
    }>;
    updateQuestion(schoolId: string, examId: string, questionId: string, body: any, userId?: string, role?: string): Promise<{
        id: string;
        isActive: boolean;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        subject: string;
        order: number;
        examId: string;
        questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
        questionText: string;
        optionA: string | null;
        optionB: string | null;
        optionC: string | null;
        optionD: string | null;
        correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
        correctText: string | null;
        caseSensitive: boolean;
    }>;
    deleteQuestion(schoolId: string, examId: string, questionId: string, userId?: string, role?: string): Promise<{
        message: string;
    }>;
    private parseCsvLine;
    importQuestions(schoolId: string, examId: string, csv: string, userId?: string, role?: string): Promise<{
        createdCount: number;
        failedCount: number;
        failed: any[];
    }>;
    listAvailableForStudent(schoolId: string, studentId: string): Promise<{
        id: string;
        description: string | null;
        _count: {
            questions: number;
        };
        subject: {
            id: string;
            name: string;
            code: string | null;
        } | null;
        grade: number;
        classId: string | null;
        sectionId: string | null;
        stream: string | null;
        status: import("@prisma/client").$Enums.PracticeExamStatus;
        title: string;
        subjectId: string | null;
        passMark: number;
        createdById: string | null;
        attempts: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            expiresAt: Date;
            studentId: string;
            status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
            submittedAt: Date | null;
            percentage: number | null;
            score: number | null;
            skippedCount: number;
            examId: string;
            startedAt: Date;
            correctCount: number;
            wrongCount: number;
        }[];
        durationMinutes: number;
        shuffleQuestions: boolean;
    }[]>;
    private extractGrade;
    private assertExamAvailableForStudent;
    startAttempt(schoolId: string, studentId: string, examId: string, accessCode: any): Promise<{
        questions: {
            correctOption?: import("@prisma/client").$Enums.PracticeExamOption | null | undefined;
            isCorrect?: boolean | null | undefined;
            id: string;
            subject: string;
            questionText: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctText: string | null | undefined;
            caseSensitive: boolean;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
        }[];
        exam?: ({
            subject: {
                id: string;
                name: string;
                code: string | null;
            } | null;
            questions: {
                id: string;
                isActive: boolean;
                schoolId: string;
                createdAt: Date;
                updatedAt: Date;
                subject: string;
                order: number;
                examId: string;
                questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
                questionText: string;
                optionA: string | null;
                optionB: string | null;
                optionC: string | null;
                optionD: string | null;
                correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
                correctText: string | null;
                caseSensitive: boolean;
            }[];
        } & {
            id: string;
            description: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            grade: number;
            classId: string | null;
            sectionId: string | null;
            academicYearId: string | null;
            stream: string | null;
            status: import("@prisma/client").$Enums.PracticeExamStatus;
            title: string;
            subjectId: string | null;
            passMark: number;
            createdById: string | null;
            accessCode: string;
            durationMinutes: number;
            shuffleQuestions: boolean;
        }) | undefined;
        answers?: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            studentId: string;
            examId: string;
            attemptId: string;
            questionId: string;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
            isCorrect: boolean | null;
        }[] | undefined;
        id?: string | undefined;
        schoolId?: string | undefined;
        createdAt?: Date | undefined;
        updatedAt?: Date | undefined;
        expiresAt?: Date | undefined;
        studentId?: string | undefined;
        status?: import("@prisma/client").$Enums.PracticeExamAttemptStatus | undefined;
        submittedAt?: Date | null | undefined;
        percentage?: number | null | undefined;
        score?: number | null | undefined;
        skippedCount?: number | undefined;
        examId?: string | undefined;
        startedAt?: Date | undefined;
        correctCount?: number | undefined;
        wrongCount?: number | undefined;
    }>;
    getAttemptForStudent(schoolId: string, studentId: string, attemptId: string): Promise<{
        questions: {
            correctOption?: import("@prisma/client").$Enums.PracticeExamOption | null | undefined;
            isCorrect?: boolean | null | undefined;
            id: string;
            subject: string;
            questionText: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctText: string | null | undefined;
            caseSensitive: boolean;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
        }[];
        exam?: ({
            subject: {
                id: string;
                name: string;
                code: string | null;
            } | null;
            questions: {
                id: string;
                isActive: boolean;
                schoolId: string;
                createdAt: Date;
                updatedAt: Date;
                subject: string;
                order: number;
                examId: string;
                questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
                questionText: string;
                optionA: string | null;
                optionB: string | null;
                optionC: string | null;
                optionD: string | null;
                correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
                correctText: string | null;
                caseSensitive: boolean;
            }[];
        } & {
            id: string;
            description: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            grade: number;
            classId: string | null;
            sectionId: string | null;
            academicYearId: string | null;
            stream: string | null;
            status: import("@prisma/client").$Enums.PracticeExamStatus;
            title: string;
            subjectId: string | null;
            passMark: number;
            createdById: string | null;
            accessCode: string;
            durationMinutes: number;
            shuffleQuestions: boolean;
        }) | undefined;
        answers?: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            studentId: string;
            examId: string;
            attemptId: string;
            questionId: string;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
            isCorrect: boolean | null;
        }[] | undefined;
        id?: string | undefined;
        schoolId?: string | undefined;
        createdAt?: Date | undefined;
        updatedAt?: Date | undefined;
        expiresAt?: Date | undefined;
        studentId?: string | undefined;
        status?: import("@prisma/client").$Enums.PracticeExamAttemptStatus | undefined;
        submittedAt?: Date | null | undefined;
        percentage?: number | null | undefined;
        score?: number | null | undefined;
        skippedCount?: number | undefined;
        examId?: string | undefined;
        startedAt?: Date | undefined;
        correctCount?: number | undefined;
        wrongCount?: number | undefined;
    }>;
    autosave(schoolId: string, studentId: string, attemptId: string, answers: AnswerInput[]): Promise<{
        message: string;
        savedCount: number;
    }>;
    private ensureOpenAttempt;
    private isAttemptExpired;
    private saveAnswers;
    submitAttempt(schoolId: string, studentId: string, attemptId: string, answers: AnswerInput[]): Promise<{
        questions: {
            correctOption?: import("@prisma/client").$Enums.PracticeExamOption | null | undefined;
            isCorrect?: boolean | null | undefined;
            id: string;
            subject: string;
            questionText: string;
            questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
            optionA: string | null;
            optionB: string | null;
            optionC: string | null;
            optionD: string | null;
            correctText: string | null | undefined;
            caseSensitive: boolean;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
        }[];
        exam?: ({
            subject: {
                id: string;
                name: string;
                code: string | null;
            } | null;
            questions: {
                id: string;
                isActive: boolean;
                schoolId: string;
                createdAt: Date;
                updatedAt: Date;
                subject: string;
                order: number;
                examId: string;
                questionType: import("@prisma/client").$Enums.PracticeExamQuestionType;
                questionText: string;
                optionA: string | null;
                optionB: string | null;
                optionC: string | null;
                optionD: string | null;
                correctOption: import("@prisma/client").$Enums.PracticeExamOption | null;
                correctText: string | null;
                caseSensitive: boolean;
            }[];
        } & {
            id: string;
            description: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            grade: number;
            classId: string | null;
            sectionId: string | null;
            academicYearId: string | null;
            stream: string | null;
            status: import("@prisma/client").$Enums.PracticeExamStatus;
            title: string;
            subjectId: string | null;
            passMark: number;
            createdById: string | null;
            accessCode: string;
            durationMinutes: number;
            shuffleQuestions: boolean;
        }) | undefined;
        answers?: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            studentId: string;
            examId: string;
            attemptId: string;
            questionId: string;
            selectedOption: import("@prisma/client").$Enums.PracticeExamOption | null;
            textAnswer: string | null;
            isFlagged: boolean;
            isCorrect: boolean | null;
        }[] | undefined;
        id?: string | undefined;
        schoolId?: string | undefined;
        createdAt?: Date | undefined;
        updatedAt?: Date | undefined;
        expiresAt?: Date | undefined;
        studentId?: string | undefined;
        status?: import("@prisma/client").$Enums.PracticeExamAttemptStatus | undefined;
        submittedAt?: Date | null | undefined;
        percentage?: number | null | undefined;
        score?: number | null | undefined;
        skippedCount?: number | undefined;
        examId?: string | undefined;
        startedAt?: Date | undefined;
        correctCount?: number | undefined;
        wrongCount?: number | undefined;
    }>;
    private finalizeAttempt;
    private gradeSavedAnswers;
    private readonly logger;
    expireStaleAttempts(): Promise<void>;
    getExamResults(schoolId: string, examId: string, userId?: string, role?: string): Promise<({
        student: {
            id: string;
            name: string;
            username: string | null;
        };
    } & {
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        expiresAt: Date;
        studentId: string;
        status: import("@prisma/client").$Enums.PracticeExamAttemptStatus;
        submittedAt: Date | null;
        percentage: number | null;
        score: number | null;
        skippedCount: number;
        examId: string;
        startedAt: Date;
        correctCount: number;
        wrongCount: number;
    })[]>;
}
export {};
