import { Role } from '../types/role.enum';

export const IT_MANAGER_FORBIDDEN_PERMISSIONS = [
  'user:create',
  'user:update',
  'user:deactivate',
  'update_users',
  'delete_users',
  'student:create',
  'student:update',
  'student:approve_enrollment',
  'parent:create',
  'parent:update',
  'parent:link_student',
  'parent:unlink_student',
  'teacher:create',
  'teacher:update',
  'employee:create',
  'employee:update',
  'employee:delete',
] as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, string[]> = {
  [Role.SUPER_ADMIN]: [
    'school:create',
    'school:read',
    'school:update',
    'school:deactivate',
    'user:create',
    'user:read',
    'user:update',
    'user:deactivate',
    'view_users',
    'view_roles',
    'manage_roles',
    'manage_permissions',
    'update_users',
    'delete_users',
    'dashboard:view',
    'event:read',
    'announcement:read',
    'academic_year:read',
    // Cross-school monitoring
    'student:read',
    'teacher:read',
    'parent:read',
    'employee:read',
    'class:read',
    'section:read',
    'finance:fee_structure:read',
    'finance:student_fees:read',
    'finance:reports:read',
    'attendance:read',
    'timetable:read',
  ],
  [Role.ADMIN]: [
    // Full school authority
    'user:create',
    'user:read',
    'user:update',
    'user:deactivate',
    'view_users',
    'update_users',
    'delete_users',
    'student:create',
    'student:read',
    'student:update',
    'document:upload',
    'student:approve_enrollment',
    'parent:create',
    'parent:read',
    'parent:update',
    'parent:link_student',
    'parent:unlink_student',
    'teacher:create',
    'teacher:read',
    'teacher:update',
    'employee:create',
    'employee:read',
    'employee:update',
    'employee:delete',
    'class:create',
    'class:read',
    'class:update',
    'class:delete',
    'section:create',
    'section:read',
    'section:update',
    'section:delete',
    'timetable:create',
    'timetable:read',
    'timetable:update',
    'timetable:manage',
    'attendance:take',
    'attendance:create',
    'attendance:read',
    'attendance:update',
    'announcement:create',
    'announcement:read',
    'announcement:update',
    'announcement:delete',
    'event:create',
    'event:read',
    'event:update',
    'event:delete',
    'dashboard:view',
    'promotion:read',
    'promotion:create',
    'report_card:create',
    'report_card:read',
    'report_card:update',
    'report_card:publish',
    'report_card:delete',
    'academic_year:create',
    'academic_year:read',
    'academic_year:update',
    'academic_year:delete',
    'finance:fee_structure:create',
    'finance:fee_structure:read',
    'finance:fee_structure:update',
    'finance:fee_structure:delete',
    'finance:student_fees:generate',
    'finance:student_fees:read',
    'finance:payments:record',
    'finance:payments:reverse',
    'finance:reports:read',
  ],
  [Role.IT_MANAGER]: [
    // Academic operations without people-management writes
    'user:read',
    'view_users',
    'student:read',
    'document:upload',
    'parent:read',
    'teacher:read',
    'employee:read',
    'class:create',
    'class:read',
    'class:update',
    'class:delete',
    'section:create',
    'section:read',
    'section:update',
    'section:delete',
    'timetable:create',
    'timetable:read',
    'timetable:update',
    'timetable:manage',
    'attendance:take',
    'attendance:create',
    'attendance:read',
    'attendance:update',
    'announcement:create',
    'announcement:read',
    'announcement:update',
    'announcement:delete',
    'event:create',
    'event:read',
    'event:update',
    'event:delete',
    'dashboard:view',
    'promotion:read',
    'promotion:create',
    'report_card:create',
    'report_card:read',
    'report_card:update',
    'report_card:publish',
    'report_card:delete',
    'academic_year:create',
    'academic_year:read',
    'academic_year:update',
    'academic_year:delete',
    'finance:fee_structure:create',
    'finance:fee_structure:read',
    'finance:fee_structure:update',
    'finance:fee_structure:delete',
    'finance:student_fees:generate',
    'finance:student_fees:read',
    'finance:payments:record',
    'finance:payments:reverse',
    'finance:reports:read',
  ],
  [Role.REGISTRAR]: [
    // User management
    'user:create',
    'user:read',
    'user:update',
    'user:deactivate',
    'view_users',
    'update_users',
    'delete_users',
    // Student management
    'student:create',
    'student:read',
    'student:update',
    'document:upload',
    'student:approve_enrollment',
    // Parent management
    'parent:create',
    'parent:read',
    'parent:update',
    'parent:link_student',
    'parent:unlink_student',
    // Teacher management
    'teacher:create',
    'teacher:read',
    'teacher:update',
    // Employee/Staff management
    'employee:create',
    'employee:read',
    'employee:update',
    'employee:delete',
    // Class & Section
    'class:create',
    'class:read',
    'class:update',
    'section:create',
    'section:read',
    'section:update',
    'section:delete',
    // Timetable
    'timetable:create',
    'timetable:read',
    'timetable:update',
    'timetable:manage',
    // Attendance
    'attendance:take',
    'attendance:create',
    'attendance:read',
    'attendance:update',
    // Announcements
    'announcement:create',
    'announcement:read',
    'announcement:update',
    'announcement:delete',
    // Events
    'event:create',
    'event:read',
    'event:update',
    'event:delete',
    // Dashboard
    'dashboard:view',
    // Grading
    'grading:read',
    'grading:update',
    'grading:approve',
    // Report cards
    'report_card:create',
    'report_card:read',
    'report_card:update',
    'report_card:publish',
    'report_card:delete',
  ],
  [Role.TEACHER]: [
    // Student management (read only)
    'student:read',
    // Parent management (read only)
    'parent:read',
    // Class & Section
    'class:read',
    'section:read',
    // Timetable
    'timetable:read',
    // Attendance
    'attendance:take',
    'attendance:read',
    // Announcements
    'announcement:read',
    // Events
    'event:read',
    // Dashboard
    'dashboard:view',
    // Teacher (own profile and assignments)
    'teacher:read',
    // Grading
    'grading:read',
    'grading:create',
    'grading:update',
  ],
  [Role.STUDENT]: [
    // Student management (own data)
    'student:read',
    // Timetable
    'timetable:read',
    // Attendance
    'attendance:read',
    // Announcements
    'announcement:read',
    // Events
    'event:read',
    // Dashboard
    'dashboard:view',
  ],
  [Role.PARENT]: [
    // Parent management (own data)
    'parent:read',
    'parent:update',
    // Timetable
    'timetable:read',
    // Attendance
    'attendance:read',
    // Dashboard
    'dashboard:view',
    // Announcements
    'announcement:read',
    // Events
    'event:read',
    // Results
    'result:read',
    // Fees
    'fee:read',
  ],
  [Role.FINANCE]: [
    // Academic Year
    'academic_year:read',
    // Fee Structure
    'finance:fee_structure:create',
    'finance:fee_structure:read',
    'finance:fee_structure:update',
    'finance:fee_structure:delete',
    // Student Fees
    'finance:student_fees:generate',
    'finance:student_fees:read',
    // Payments
    'finance:payments:record',
    'finance:payments:reverse',
    // Reports
    'finance:reports:read',
    // Payroll
    'finance:payroll:read',
    'finance:payroll:manage',
    'finance:payroll:approve',
    'finance:payroll:pay',
    // Dashboard
    'dashboard:view',
    // Student (read only)
    'student:read',
    // Parent (read only)
    'parent:read',
    // All student queries
    'student:read',
    // Events and Announcements
    'event:read',
    'announcement:read',
  ],
};
