import { PrismaService } from '../prisma/prisma.service';
import { CacheService } from '../infrastructure/cache/cache.service';
import { CredentialService } from '../credential/credential.service';
import { SubscriptionService } from '../subscription/subscription.service';
import { AuditRequestContext, AuditService, type AuditActor } from '../audit/audit.service';
import { StorageService } from '../storage/storage.service';
export declare const SCHOOL_SETTING_KEYS: {
    readonly CURRICULUM_TYPE: "curriculum_type";
    readonly CALENDAR_TYPE: "calendar_type";
    readonly GRADE_SYSTEM: "grade_system";
    readonly FEE_STRUCTURE_MODE: "fee_structure_mode";
    readonly FEE_PAYMENT_DUE_DAY: "fee_payment_due_day";
    readonly FEE_DAILY_PENALTY_AMOUNT: "fee_daily_penalty_amount";
    readonly FAMILY_DISCOUNT_ENABLED: "family_discount_enabled";
    readonly FAMILY_DISCOUNT_MIN_STUDENTS: "family_discount_min_students";
    readonly FAMILY_DISCOUNT_PERCENT: "family_discount_percent";
    readonly FAMILY_DISCOUNT_FEE_TYPES: "family_discount_fee_types";
    readonly PARENT_VIEW_GRADES: "parent_view_grades";
    readonly ATTENDANCE_CUTOFF_TIME: "ATTENDANCE_CUTOFF_TIME";
    readonly SCHOOL_START_TIME: "SCHOOL_START_TIME";
    readonly SCHOOL_END_TIME: "SCHOOL_END_TIME";
    readonly MAX_PERIODS_PER_DAY: "MAX_PERIODS_PER_DAY";
    readonly DEFAULT_SECTION_CAPACITY: "DEFAULT_SECTION_CAPACITY";
    readonly SCHOOL_NAME: "school_name";
    readonly SCHOOL_ADDRESS: "school_address";
    readonly SCHOOL_PHONE: "school_phone";
    readonly SCHOOL_EMAIL: "school_email";
    readonly LOGO_URL: "logo_url";
    readonly LOGIN_IMAGE_URL: "login_image_url";
    readonly THEME_COLOR: "theme_color";
    readonly BRAND_COLOR_IN_NAVIGATION: "BRAND_COLOR_IN_NAVIGATION";
    readonly CUSTOM_BRANDING: "CUSTOM_BRANDING";
    readonly CERTIFICATE_SETTINGS: "CERTIFICATE_SETTINGS";
    readonly CERTIFICATE_TEMPLATE: "certificate_template";
    readonly ID_CARD_TEMPLATE: "id_card_template";
    readonly TEACHER_PORTAL_ACCESS: "TEACHER_PORTAL_ACCESS";
    readonly STUDENT_PORTAL_ACCESS: "STUDENT_PORTAL_ACCESS";
    readonly PARENT_PORTAL_ACCESS: "PARENT_PORTAL_ACCESS";
    readonly FINANCE_PORTAL_ACCESS: "FINANCE_PORTAL_ACCESS";
    readonly REGISTRAR_PORTAL_ACCESS: "REGISTRAR_PORTAL_ACCESS";
    readonly SCHOOL_STARTS_AT: "SCHOOL_STARTS_AT";
    readonly REGISTRATION_STARTS_AT: "REGISTRATION_STARTS_AT";
    readonly MAINTENANCE_MODE: "MAINTENANCE_MODE";
    readonly PROMOTION_MIN_AVERAGE_GRADE: "PROMOTION_MIN_AVERAGE_GRADE";
    readonly PROMOTION_MIN_ATTENDANCE: "PROMOTION_MIN_ATTENDANCE";
    readonly PROMOTION_ALLOW_FAILED_SUBJECTS: "PROMOTION_ALLOW_FAILED_SUBJECTS";
};
type SchoolSettingMutationContext = {
    actor?: AuditActor | null;
    request?: AuditRequestContext | null;
    source?: 'single' | 'batch' | 'upload' | 'delete';
};
export declare class SchoolSettingsService {
    private readonly prisma;
    private readonly cacheService;
    private readonly credentialService;
    private readonly subscriptionService;
    private readonly auditService;
    private readonly storageService;
    constructor(prisma: PrismaService, cacheService: CacheService, credentialService: CredentialService, subscriptionService: SubscriptionService, auditService: AuditService, storageService: StorageService);
    private readonly allowedCalendarTypes;
    private readonly allowedCurriculumTypes;
    private readonly allowedGradeSystems;
    private readonly allowedFeeStructureModes;
    private getSectionNameByIndex;
    private normalizeStudentName;
    private readonly booleanKeys;
    private readonly tierLevels;
    private readonly settingRequirements;
    private readonly allowedSettingKeys;
    private getSettingCacheKey;
    private getAllSettingsCacheKey;
    private invalidateCache;
    private parseStoredValue;
    private serializeSettingValue;
    private timeToMinutes;
    private canonicalizeSettingKey;
    private assertAllowedSettingKey;
    private getSettingKeyAliases;
    private normalizeSettingValue;
    private enforceSubscriptionAccess;
    private validateSchoolDayBounds;
    private validateMaxPeriodsPerDay;
    private cleanupLocalUpload;
    private auditSettingChange;
    uploadLoginImage(schoolId: string, file: Express.Multer.File, context?: SchoolSettingMutationContext): Promise<string>;
    private validateCalendarTypeOneTimeChange;
    private validateGradeSystemOneTimeChange;
    private validateCurriculumTypeOneTimeChange;
    getSetting(schoolId: string, key: string): Promise<any>;
    getAllSettings(schoolId: string): Promise<Record<string, any>>;
    setSetting(schoolId: string, key: string, value: any, context?: SchoolSettingMutationContext): Promise<{
        value: any;
        id: string;
        schoolId: string;
        updatedAt: Date;
        key: string;
    }>;
    private syncSectionCapacities;
    private autoCreateTermsForAcademicYears;
    private autoCreateGradeLevels;
    ensureDefaultClassesForAcademicYear(schoolId: string, academicYearId: string): Promise<{
        message: string;
    }>;
    private buildGradeLevelsFromRange;
    getGradeLevelsForSchool(schoolId: string): Promise<{
        name: string;
        level: number;
    }[]>;
    deleteSetting(schoolId: string, key: string, context?: SchoolSettingMutationContext): Promise<{
        message: string;
    }>;
    getEffectiveSetting(schoolId: string, key: string, platformValue?: any, systemDefault?: any): Promise<any>;
    batchUpdate(schoolId: string, settings: Record<string, any>, context?: SchoolSettingMutationContext): Promise<any[]>;
    getCurriculumType(schoolId: string): Promise<string>;
    getGradeSystem(schoolId: string): Promise<string>;
    getAcademicConfiguration(schoolId: string): Promise<{
        curriculumType: string;
        gradeSystem: string;
        activeAcademicYear: any;
        periods: any[];
    }>;
}
export {};
