import { PrismaService } from '../prisma/prisma.service';
import { EnrollmentStatus } from '@prisma/client';
import { AutoAssignmentService } from '../auto-assignment/auto-assignment.service';
import { CredentialService } from '../credential/credential.service';
export interface CreateStudentDto {
    email: string;
    name: string;
    academicYear: string;
    gradeId: string;
    stream?: string | null;
    gender?: string;
    address?: string;
    phone?: string;
    motherName?: string;
    motherPhone?: string;
    emergencyContact?: {
        name: string;
        phone: string;
        relationship: string;
    };
    guardianName?: string;
    guardianPhone?: string;
    guardianEmail?: string;
    photo?: string;
    documents?: {
        type: string;
        fileUrl: string;
        title?: string;
    }[];
}
export interface UpdateStudentDto {
    name?: string;
    gender?: string;
    stream?: string | null;
    address?: string;
    phone?: string;
    motherName?: string;
    motherPhone?: string;
    dateOfBirth?: string;
    faydaNumber?: string | null;
    emergencyContact?: {
        name: string;
        phone: string;
        relationship: string;
    };
    guardianName?: string;
    guardianPhone?: string;
    guardianEmail?: string;
    photo?: string;
    documents?: {
        type: string;
        fileUrl: string;
        title?: string;
    }[];
}
export interface ApproveEnrollmentDto {
    className: string;
    section: string;
    rollNumber: string;
}
export interface AssignClassDto {
    className: string;
    section: string;
    rollNumber: string;
    classId?: string;
    sectionId?: string;
    stream?: string | null;
}
export declare class RegistrarService {
    private prismaService;
    private autoAssignmentService;
    private credentialService;
    constructor(prismaService: PrismaService, autoAssignmentService: AutoAssignmentService, credentialService: CredentialService);
    private normalizeStudentStream;
    private extractGradeFromClassName;
    private resolveSectionWithCapacity;
    createStudent(createStudentDto: CreateStudentDto, schoolId: string, createdById: string): Promise<{
        user: {
            id: string;
            name: string;
            role: import("@prisma/client").$Enums.Role;
            email: string | null;
            username: string | null;
            password: string;
            isActive: boolean;
            phone: string | null;
            avatarUrl: string | null;
            theme: import("@prisma/client").$Enums.ThemePreference;
            language: string;
            lastLoginAt: Date | null;
            schoolId: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            mustChangePassword: boolean;
        };
        studentProfile: {
            id: string;
            phone: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string | null;
            section: string | null;
            address: string | null;
            userId: string;
            studentId: string;
            stream: string | null;
            studentCode: string;
            faydaNumber: string | null;
            enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
            className: string | null;
            rollNumber: string | null;
            gender: string | null;
            motherName: string | null;
            motherPhone: string | null;
            emergencyContact: string | null;
            medicalInfo: string | null;
            nationality: string | null;
        };
        enrollment: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string;
            grade: number | null;
            studentId: string;
            gradeId: string | null;
            status: import("@prisma/client").$Enums.EnrollmentStatus;
            metadata: string | null;
            rejectionReason: string | null;
        };
        studentCode: string;
        username: string;
        temporaryPassword: string;
    }>;
    getStudents(schoolId: string, filters?: {
        status?: EnrollmentStatus;
        grade?: number;
    }): Promise<{
        enrollment: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string;
            grade: number | null;
            studentId: string;
            gradeId: string | null;
            status: import("@prisma/client").$Enums.EnrollmentStatus;
            metadata: string | null;
            rejectionReason: string | null;
        } | undefined;
        user: {
            id: string;
            name: string;
            email: string | null;
            isActive: boolean;
        };
        id: string;
        phone: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedById: string | null;
        documents: string | null;
        academicYear: string | null;
        section: string | null;
        address: string | null;
        userId: string;
        studentId: string;
        stream: string | null;
        studentCode: string;
        faydaNumber: string | null;
        enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
        className: string | null;
        rollNumber: string | null;
        gender: string | null;
        motherName: string | null;
        motherPhone: string | null;
        emergencyContact: string | null;
        medicalInfo: string | null;
        nationality: string | null;
    }[]>;
    getStudentById(studentId: string, schoolId: string): Promise<{
        enrollment: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string;
            grade: number | null;
            studentId: string;
            gradeId: string | null;
            status: import("@prisma/client").$Enums.EnrollmentStatus;
            metadata: string | null;
            rejectionReason: string | null;
        } | null;
        user: {
            id: string;
            name: string;
            email: string | null;
            isActive: boolean;
        };
        id: string;
        phone: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedById: string | null;
        documents: string | null;
        academicYear: string | null;
        section: string | null;
        address: string | null;
        userId: string;
        studentId: string;
        stream: string | null;
        studentCode: string;
        faydaNumber: string | null;
        enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
        className: string | null;
        rollNumber: string | null;
        gender: string | null;
        motherName: string | null;
        motherPhone: string | null;
        emergencyContact: string | null;
        medicalInfo: string | null;
        nationality: string | null;
    }>;
    updateStudent(studentId: string, schoolId: string, updateStudentDto: UpdateStudentDto): Promise<{
        id: string;
        phone: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedById: string | null;
        documents: string | null;
        academicYear: string | null;
        section: string | null;
        address: string | null;
        userId: string;
        studentId: string;
        stream: string | null;
        studentCode: string;
        faydaNumber: string | null;
        enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
        className: string | null;
        rollNumber: string | null;
        gender: string | null;
        motherName: string | null;
        motherPhone: string | null;
        emergencyContact: string | null;
        medicalInfo: string | null;
        nationality: string | null;
    }>;
    getPendingEnrollments(schoolId: string): Promise<{
        studentProfile: {
            id: string;
            phone: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string | null;
            section: string | null;
            address: string | null;
            userId: string;
            studentId: string;
            stream: string | null;
            studentCode: string;
            faydaNumber: string | null;
            enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
            className: string | null;
            rollNumber: string | null;
            gender: string | null;
            motherName: string | null;
            motherPhone: string | null;
            emergencyContact: string | null;
            medicalInfo: string | null;
            nationality: string | null;
        } | undefined;
        student: {
            id: string;
            name: string;
            email: string | null;
        };
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedById: string | null;
        documents: string | null;
        academicYear: string;
        grade: number | null;
        studentId: string;
        gradeId: string | null;
        status: import("@prisma/client").$Enums.EnrollmentStatus;
        metadata: string | null;
        rejectionReason: string | null;
    }[]>;
    getEnrollments(schoolId: string, status?: string, page?: number): Promise<{
        data: {
            user: {
                id: string;
                name: string;
                email: string | null;
                phone: string | null;
            };
            studentProfile: {
                id: string;
                phone: string | null;
                schoolId: string;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                deletedById: string | null;
                documents: string | null;
                academicYear: string | null;
                section: string | null;
                address: string | null;
                userId: string;
                studentId: string;
                stream: string | null;
                studentCode: string;
                faydaNumber: string | null;
                enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
                className: string | null;
                rollNumber: string | null;
                gender: string | null;
                motherName: string | null;
                motherPhone: string | null;
                emergencyContact: string | null;
                medicalInfo: string | null;
                nationality: string | null;
            } | undefined;
            student: {
                id: string;
                name: string;
                email: string | null;
                phone: string | null;
            };
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string;
            grade: number | null;
            studentId: string;
            gradeId: string | null;
            status: import("@prisma/client").$Enums.EnrollmentStatus;
            metadata: string | null;
            rejectionReason: string | null;
        }[];
        total: number;
        page: number;
        totalPages: number;
    }>;
    approveEnrollment(enrollmentId: string, schoolId: string, approveData: ApproveEnrollmentDto): Promise<{
        message: string;
    }>;
    approveEnrollmentAuto(enrollmentId: string, schoolId: string): Promise<import("../auto-assignment/auto-assignment.service").AutoAssignmentResult>;
    rejectEnrollment(enrollmentId: string, schoolId: string, rejectionReason: string): Promise<{
        message: string;
    }>;
    assignClass(studentId: string, schoolId: string, assignData: AssignClassDto): Promise<{
        message: string;
        studentId: string;
        className: string;
        stream: string | null;
        section: string;
        rollNumber: string;
    }>;
    uploadDocuments(studentId: string, schoolId: string, documents: any[]): Promise<{
        message: string;
        studentId: string;
        documentCount: number;
    }>;
    private generateStudentCode;
    private generateTempPassword;
}
