import { RegistrarService } from './registrar.service';
export declare class RegistrarController {
    private readonly registrarService;
    constructor(registrarService: RegistrarService);
    createStudent(body: {
        email: string;
        name: string;
        academicYear: string;
        gradeId: string;
        gender?: string;
        stream?: string | null;
        address?: string;
        phone?: string;
        emergencyContact?: {
            name: string;
            phone: string;
            relationship: string;
        };
        guardianName?: string;
        guardianPhone?: string;
        guardianEmail?: string;
        documents?: any[];
    }, req: any): Promise<{
        user: {
            id: string;
            name: string;
            role: import("@prisma/client").$Enums.Role;
            email: string | null;
            username: string | null;
            password: string;
            isActive: boolean;
            phone: string | null;
            avatarUrl: string | null;
            theme: import("@prisma/client").$Enums.ThemePreference;
            language: string;
            lastLoginAt: Date | null;
            schoolId: string | null;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            mustChangePassword: boolean;
        };
        studentProfile: {
            id: string;
            phone: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string | null;
            section: string | null;
            address: string | null;
            userId: string;
            studentId: string;
            stream: string | null;
            studentCode: string;
            faydaNumber: string | null;
            enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
            className: string | null;
            rollNumber: string | null;
            gender: string | null;
            motherName: string | null;
            motherPhone: string | null;
            emergencyContact: string | null;
            medicalInfo: string | null;
            nationality: string | null;
        };
        enrollment: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string;
            grade: number | null;
            studentId: string;
            gradeId: string | null;
            status: import("@prisma/client").$Enums.EnrollmentStatus;
            metadata: string | null;
            rejectionReason: string | null;
        };
        studentCode: string;
        username: string;
        temporaryPassword: string;
    }>;
    getStudents(req: any, status?: string, grade?: string): Promise<{
        enrollment: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string;
            grade: number | null;
            studentId: string;
            gradeId: string | null;
            status: import("@prisma/client").$Enums.EnrollmentStatus;
            metadata: string | null;
            rejectionReason: string | null;
        } | undefined;
        user: {
            id: string;
            name: string;
            email: string | null;
            isActive: boolean;
        };
        id: string;
        phone: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedById: string | null;
        documents: string | null;
        academicYear: string | null;
        section: string | null;
        address: string | null;
        userId: string;
        studentId: string;
        stream: string | null;
        studentCode: string;
        faydaNumber: string | null;
        enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
        className: string | null;
        rollNumber: string | null;
        gender: string | null;
        motherName: string | null;
        motherPhone: string | null;
        emergencyContact: string | null;
        medicalInfo: string | null;
        nationality: string | null;
    }[]>;
    getStudentById(studentId: string, req: any): Promise<{
        enrollment: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string;
            grade: number | null;
            studentId: string;
            gradeId: string | null;
            status: import("@prisma/client").$Enums.EnrollmentStatus;
            metadata: string | null;
            rejectionReason: string | null;
        } | null;
        user: {
            id: string;
            name: string;
            email: string | null;
            isActive: boolean;
        };
        id: string;
        phone: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedById: string | null;
        documents: string | null;
        academicYear: string | null;
        section: string | null;
        address: string | null;
        userId: string;
        studentId: string;
        stream: string | null;
        studentCode: string;
        faydaNumber: string | null;
        enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
        className: string | null;
        rollNumber: string | null;
        gender: string | null;
        motherName: string | null;
        motherPhone: string | null;
        emergencyContact: string | null;
        medicalInfo: string | null;
        nationality: string | null;
    }>;
    updateStudent(studentId: string, body: {
        name?: string;
        gender?: string;
        stream?: string | null;
        address?: string;
        phone?: string;
        motherName?: string;
        motherPhone?: string;
        dateOfBirth?: string;
        faydaNumber?: string | null;
        emergencyContact?: {
            name: string;
            phone: string;
            relationship: string;
        };
        guardianName?: string;
        guardianPhone?: string;
        guardianEmail?: string;
        documents?: any[];
    }, req: any): Promise<{
        id: string;
        phone: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedById: string | null;
        documents: string | null;
        academicYear: string | null;
        section: string | null;
        address: string | null;
        userId: string;
        studentId: string;
        stream: string | null;
        studentCode: string;
        faydaNumber: string | null;
        enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
        className: string | null;
        rollNumber: string | null;
        gender: string | null;
        motherName: string | null;
        motherPhone: string | null;
        emergencyContact: string | null;
        medicalInfo: string | null;
        nationality: string | null;
    }>;
    getPendingEnrollments(req: any): Promise<{
        studentProfile: {
            id: string;
            phone: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string | null;
            section: string | null;
            address: string | null;
            userId: string;
            studentId: string;
            stream: string | null;
            studentCode: string;
            faydaNumber: string | null;
            enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
            className: string | null;
            rollNumber: string | null;
            gender: string | null;
            motherName: string | null;
            motherPhone: string | null;
            emergencyContact: string | null;
            medicalInfo: string | null;
            nationality: string | null;
        } | undefined;
        student: {
            id: string;
            name: string;
            email: string | null;
        };
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        deletedAt: Date | null;
        deletedById: string | null;
        documents: string | null;
        academicYear: string;
        grade: number | null;
        studentId: string;
        gradeId: string | null;
        status: import("@prisma/client").$Enums.EnrollmentStatus;
        metadata: string | null;
        rejectionReason: string | null;
    }[]>;
    getEnrollments(req: any, status?: string, page?: string): Promise<{
        data: {
            user: {
                id: string;
                name: string;
                email: string | null;
                phone: string | null;
            };
            studentProfile: {
                id: string;
                phone: string | null;
                schoolId: string;
                createdAt: Date;
                updatedAt: Date;
                deletedAt: Date | null;
                deletedById: string | null;
                documents: string | null;
                academicYear: string | null;
                section: string | null;
                address: string | null;
                userId: string;
                studentId: string;
                stream: string | null;
                studentCode: string;
                faydaNumber: string | null;
                enrollmentStatus: import("@prisma/client").$Enums.EnrollmentStatus;
                className: string | null;
                rollNumber: string | null;
                gender: string | null;
                motherName: string | null;
                motherPhone: string | null;
                emergencyContact: string | null;
                medicalInfo: string | null;
                nationality: string | null;
            } | undefined;
            student: {
                id: string;
                name: string;
                email: string | null;
                phone: string | null;
            };
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            deletedAt: Date | null;
            deletedById: string | null;
            documents: string | null;
            academicYear: string;
            grade: number | null;
            studentId: string;
            gradeId: string | null;
            status: import("@prisma/client").$Enums.EnrollmentStatus;
            metadata: string | null;
            rejectionReason: string | null;
        }[];
        total: number;
        page: number;
        totalPages: number;
    }>;
    approveEnrollment(enrollmentId: string, body: {
        className: string;
        section: string;
        rollNumber: string;
        classId?: string;
        sectionId?: string;
        stream?: string | null;
    }, req: any): Promise<{
        message: string;
    }>;
    approveEnrollmentAuto(enrollmentId: string, req: any): Promise<import("../auto-assignment/auto-assignment.service").AutoAssignmentResult>;
    rejectEnrollment(enrollmentId: string, rejectionReason: string, req: any): Promise<{
        message: string;
    }>;
    assignClass(studentId: string, body: {
        className: string;
        section: string;
        rollNumber: string;
    }, req: any): Promise<{
        message: string;
        studentId: string;
        className: string;
        stream: string | null;
        section: string;
        rollNumber: string;
    }>;
    uploadDocuments(studentId: string, documents: any[], req: any): Promise<{
        message: string;
        studentId: string;
        documentCount: number;
    }>;
}
