import { PrismaService } from '../prisma/prisma.service';
import { SchoolSettingsService } from '../school-settings/school-settings.service';
import { EventBusService } from '../core/events/event-bus.service';
import { CredentialService } from '../credential/credential.service';
export interface CreateEnrollmentRequestDto {
    schoolId: string;
    academicYearId: string;
    firstName: string;
    middleName?: string;
    lastName: string;
    dateOfBirth: string;
    gender: string;
    faydaNumber: string;
    nationality?: string;
    email?: string;
    phone?: string;
    address?: string;
    previousSchool?: string;
    previousGrade?: number;
    transferCertificate?: boolean;
    parentFirstName: string;
    parentLastName: string;
    parentPhone: string;
    parentEmail?: string;
    parentRelation: string;
    requestedGrade: number;
    requestedStream?: string;
    documents?: Record<string, boolean>;
}
export interface EnrollmentQueryDto {
    schoolId: string;
    academicYearId?: string;
    status?: string;
    grade?: number;
    search?: string;
    page?: number;
    limit?: number;
}
export declare class EnrollmentRequestService {
    private readonly prisma;
    private readonly schoolSettings;
    private readonly eventBus;
    private readonly credentialService;
    constructor(prisma: PrismaService, schoolSettings: SchoolSettingsService, eventBus: EventBusService, credentialService: CredentialService);
    getPublicSchools(): Promise<{
        id: string;
        name: string;
        code: string | null;
        publicUrlSlug: string;
        logoUrl: string | null;
        accentColor: string | null;
        loginImageUrl: string | null;
        schoolStartsAt: string | null;
        registrationStartsAt: string | null;
        isMaintenance: boolean;
    }[]>;
    getPublicSchoolById(id: string): Promise<{
        id: string;
        name: string;
        code: string | null;
        publicUrlSlug: string;
        logoUrl: string | null;
        email: string;
        phone: string | null;
        address: string | null;
        isActive: boolean;
        accentColor: string | null;
        loginImageUrl: string | null;
        schoolStartsAt: string | null;
        registrationStartsAt: string | null;
        isMaintenance: boolean;
    } | null>;
    getPublicSchoolByUrlSlug(publicUrlSlug: string): Promise<{
        id: string;
        name: string;
        code: string | null;
        publicUrlSlug: string;
        logoUrl: string | null;
        email: string;
        phone: string | null;
        address: string | null;
        isActive: boolean;
        accentColor: string | null;
        loginImageUrl: string | null;
        schoolStartsAt: string | null;
        registrationStartsAt: string | null;
        isMaintenance: boolean;
    } | null>;
    getAvailableGrades(schoolId: string): Promise<{
        grade: number;
    }[]>;
    private assertRequestedGradeAllowed;
    private calculateRollNumber;
    private generateStudentUsername;
    private findBestSection;
    private normalizeStudentStream;
    createEnrollmentRequest(dto: CreateEnrollmentRequestDto): Promise<{
        referenceNumber: string;
        id: string;
        email: string | null;
        phone: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        documents: string | null;
        address: string | null;
        userId: string | null;
        academicYearId: string;
        faydaNumber: string | null;
        gender: string;
        nationality: string | null;
        status: import("@prisma/client").$Enums.EnrollmentRequestStatus;
        rejectionReason: string | null;
        approvedBy: string | null;
        dateOfBirth: Date;
        firstName: string;
        middleName: string | null;
        lastName: string;
        previousSchool: string | null;
        previousGrade: number | null;
        transferCertificate: boolean;
        parentFirstName: string;
        parentLastName: string;
        parentPhone: string;
        parentEmail: string | null;
        parentRelation: string;
        requestedGrade: number;
        requestedStream: string | null;
        requestedSection: string | null;
        approvedAt: Date | null;
        allocatedClassId: string | null;
        allocatedSectionId: string | null;
        allocatedRollNumber: number | null;
        allocatedStudentCode: string | null;
    }>;
    listEnrollmentRequests(query: EnrollmentQueryDto): Promise<{
        total: number;
        page: number;
        limit: number;
        data: ({
            academicYear: {
                id: string;
                name: string;
            };
            allocatedClass: {
                id: string;
                name: string;
            } | null;
            allocatedSection: {
                id: string;
                name: string;
            } | null;
        } & {
            id: string;
            email: string | null;
            phone: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            documents: string | null;
            address: string | null;
            userId: string | null;
            academicYearId: string;
            faydaNumber: string | null;
            gender: string;
            nationality: string | null;
            status: import("@prisma/client").$Enums.EnrollmentRequestStatus;
            rejectionReason: string | null;
            approvedBy: string | null;
            dateOfBirth: Date;
            firstName: string;
            middleName: string | null;
            lastName: string;
            previousSchool: string | null;
            previousGrade: number | null;
            transferCertificate: boolean;
            parentFirstName: string;
            parentLastName: string;
            parentPhone: string;
            parentEmail: string | null;
            parentRelation: string;
            requestedGrade: number;
            requestedStream: string | null;
            requestedSection: string | null;
            approvedAt: Date | null;
            allocatedClassId: string | null;
            allocatedSectionId: string | null;
            allocatedRollNumber: number | null;
            allocatedStudentCode: string | null;
        })[];
    }>;
    getEnrollmentRequest(id: string, schoolId: string): Promise<{
        user: {
            id: string;
            email: string | null;
        } | null;
        academicYear: {
            id: string;
            name: string;
        };
        allocatedClass: {
            id: string;
            name: string;
            section: string;
        } | null;
        allocatedSection: {
            id: string;
            name: string;
        } | null;
    } & {
        id: string;
        email: string | null;
        phone: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        documents: string | null;
        address: string | null;
        userId: string | null;
        academicYearId: string;
        faydaNumber: string | null;
        gender: string;
        nationality: string | null;
        status: import("@prisma/client").$Enums.EnrollmentRequestStatus;
        rejectionReason: string | null;
        approvedBy: string | null;
        dateOfBirth: Date;
        firstName: string;
        middleName: string | null;
        lastName: string;
        previousSchool: string | null;
        previousGrade: number | null;
        transferCertificate: boolean;
        parentFirstName: string;
        parentLastName: string;
        parentPhone: string;
        parentEmail: string | null;
        parentRelation: string;
        requestedGrade: number;
        requestedStream: string | null;
        requestedSection: string | null;
        approvedAt: Date | null;
        allocatedClassId: string | null;
        allocatedSectionId: string | null;
        allocatedRollNumber: number | null;
        allocatedStudentCode: string | null;
    }>;
    approveEnrollment(id: string, schoolId: string, approvedBy: string): Promise<{
        enrollment: {
            id: string;
            email: string | null;
            phone: string | null;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            documents: string | null;
            address: string | null;
            userId: string | null;
            academicYearId: string;
            faydaNumber: string | null;
            gender: string;
            nationality: string | null;
            status: import("@prisma/client").$Enums.EnrollmentRequestStatus;
            rejectionReason: string | null;
            approvedBy: string | null;
            dateOfBirth: Date;
            firstName: string;
            middleName: string | null;
            lastName: string;
            previousSchool: string | null;
            previousGrade: number | null;
            transferCertificate: boolean;
            parentFirstName: string;
            parentLastName: string;
            parentPhone: string;
            parentEmail: string | null;
            parentRelation: string;
            requestedGrade: number;
            requestedStream: string | null;
            requestedSection: string | null;
            approvedAt: Date | null;
            allocatedClassId: string | null;
            allocatedSectionId: string | null;
            allocatedRollNumber: number | null;
            allocatedStudentCode: string | null;
        };
        credentials: {
            student: {
                userId: string;
                username: string;
                password: string;
                studentCode: string;
                class: string;
                section: any;
                rollNumber: number;
            };
            parent: {
                userId: string;
                username: string | undefined;
                password: string;
                phone: string;
            };
        };
    }>;
    rejectEnrollment(id: string, schoolId: string, reason: string): Promise<{
        id: string;
        email: string | null;
        phone: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        documents: string | null;
        address: string | null;
        userId: string | null;
        academicYearId: string;
        faydaNumber: string | null;
        gender: string;
        nationality: string | null;
        status: import("@prisma/client").$Enums.EnrollmentRequestStatus;
        rejectionReason: string | null;
        approvedBy: string | null;
        dateOfBirth: Date;
        firstName: string;
        middleName: string | null;
        lastName: string;
        previousSchool: string | null;
        previousGrade: number | null;
        transferCertificate: boolean;
        parentFirstName: string;
        parentLastName: string;
        parentPhone: string;
        parentEmail: string | null;
        parentRelation: string;
        requestedGrade: number;
        requestedStream: string | null;
        requestedSection: string | null;
        approvedAt: Date | null;
        allocatedClassId: string | null;
        allocatedSectionId: string | null;
        allocatedRollNumber: number | null;
        allocatedStudentCode: string | null;
    }>;
    waitlistEnrollment(id: string, schoolId: string): Promise<{
        id: string;
        email: string | null;
        phone: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        documents: string | null;
        address: string | null;
        userId: string | null;
        academicYearId: string;
        faydaNumber: string | null;
        gender: string;
        nationality: string | null;
        status: import("@prisma/client").$Enums.EnrollmentRequestStatus;
        rejectionReason: string | null;
        approvedBy: string | null;
        dateOfBirth: Date;
        firstName: string;
        middleName: string | null;
        lastName: string;
        previousSchool: string | null;
        previousGrade: number | null;
        transferCertificate: boolean;
        parentFirstName: string;
        parentLastName: string;
        parentPhone: string;
        parentEmail: string | null;
        parentRelation: string;
        requestedGrade: number;
        requestedStream: string | null;
        requestedSection: string | null;
        approvedAt: Date | null;
        allocatedClassId: string | null;
        allocatedSectionId: string | null;
        allocatedRollNumber: number | null;
        allocatedStudentCode: string | null;
    }>;
    cancelEnrollment(id: string, schoolId: string): Promise<{
        id: string;
        email: string | null;
        phone: string | null;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        documents: string | null;
        address: string | null;
        userId: string | null;
        academicYearId: string;
        faydaNumber: string | null;
        gender: string;
        nationality: string | null;
        status: import("@prisma/client").$Enums.EnrollmentRequestStatus;
        rejectionReason: string | null;
        approvedBy: string | null;
        dateOfBirth: Date;
        firstName: string;
        middleName: string | null;
        lastName: string;
        previousSchool: string | null;
        previousGrade: number | null;
        transferCertificate: boolean;
        parentFirstName: string;
        parentLastName: string;
        parentPhone: string;
        parentEmail: string | null;
        parentRelation: string;
        requestedGrade: number;
        requestedStream: string | null;
        requestedSection: string | null;
        approvedAt: Date | null;
        allocatedClassId: string | null;
        allocatedSectionId: string | null;
        allocatedRollNumber: number | null;
        allocatedStudentCode: string | null;
    }>;
    getEnrollmentStats(schoolId: string, academicYearId?: string): Promise<{
        total: number;
        pending: number;
        approved: number;
        rejected: number;
        waitlisted: number;
        byGrade: {
            grade: number;
            count: number;
        }[];
    }>;
    checkGradeCapacity(schoolId: string, grade: number): Promise<{
        exists: boolean;
        message: string;
        grade?: undefined;
        totalCapacity?: undefined;
        totalEnrolled?: undefined;
        totalAvailable?: undefined;
        isFull?: undefined;
        sections?: undefined;
    } | {
        exists: boolean;
        grade: string;
        totalCapacity: number;
        totalEnrolled: number;
        totalAvailable: number;
        isFull: boolean;
        sections: {
            name: string;
            capacity: number;
            enrolled: number;
            available: number;
        }[];
        message?: undefined;
    }>;
    getEnrollmentStatus(schoolId: string): Promise<{
        isOpen: boolean;
        academicYearId: string | null;
        academicYearName: string | null;
        message: string;
    }>;
}
