import { LessonService } from './lesson.service';
import { UpdateLessonDto, LessonQueryDto } from './dto';
import { CreateLessonBundleDto, UpdateLessonBundleDto, SubmitHomeworkDto, GradeHomeworkDto, LessonCoverageQueryDto } from './dto/create-lesson-bundle.dto';
export declare class LessonController {
    private readonly lessonService;
    constructor(lessonService: LessonService);
    createBundle(createLessonBundleDto: CreateLessonBundleDto, req: any): Promise<{
        lesson: any;
        resources: any[];
    }>;
    updateBundle(id: string, updateLessonBundleDto: UpdateLessonBundleDto, req: any): Promise<{
        lesson: {
            subject: {
                grade: number | null;
                id: string;
                schoolId: string;
                createdAt: Date;
                updatedAt: Date;
                name: string;
                code: string | null;
                isActive: boolean;
                description: string | null;
                credits: number | null;
                colorCode: string | null;
            } | null;
            teacher: {
                id: string;
                name: string;
                email: string | null;
            } | null;
        } & {
            grade: number | null;
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            classId: string | null;
            sectionId: string | null;
            academicYearId: string | null;
            status: import("@prisma/client").$Enums.LessonStatus;
            title: string;
            type: import("@prisma/client").$Enums.ContentType;
            description: string | null;
            isLocked: boolean;
            subjectId: string | null;
            teacherId: string | null;
            periodNumber: number | null;
            maxMarks: number | null;
            dueDate: Date | null;
            createdById: string | null;
            attachments: string | null;
            instructions: string | null;
            objective: string | null;
            lessonContent: string | null;
            stream: string | null;
            semesterId: string | null;
            lessonDate: Date | null;
            totalPoints: number | null;
            unitNumber: number | null;
            topicName: string | null;
            topicId: string | null;
            competency: string | null;
            syllabusMappingId: string | null;
            isExamPrep: boolean;
            sectionName: string | null;
            reviewedBy: string | null;
            reviewedAt: Date | null;
        };
    }>;
    submitForReview(id: string, req: any): Promise<{
        subject: {
            grade: number | null;
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string | null;
            isActive: boolean;
            description: string | null;
            credits: number | null;
            colorCode: string | null;
        } | null;
        teacher: {
            id: string;
            name: string;
            email: string | null;
        } | null;
    } & {
        grade: number | null;
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        status: import("@prisma/client").$Enums.LessonStatus;
        title: string;
        type: import("@prisma/client").$Enums.ContentType;
        description: string | null;
        isLocked: boolean;
        subjectId: string | null;
        teacherId: string | null;
        periodNumber: number | null;
        maxMarks: number | null;
        dueDate: Date | null;
        createdById: string | null;
        attachments: string | null;
        instructions: string | null;
        objective: string | null;
        lessonContent: string | null;
        stream: string | null;
        semesterId: string | null;
        lessonDate: Date | null;
        totalPoints: number | null;
        unitNumber: number | null;
        topicName: string | null;
        topicId: string | null;
        competency: string | null;
        syllabusMappingId: string | null;
        isExamPrep: boolean;
        sectionName: string | null;
        reviewedBy: string | null;
        reviewedAt: Date | null;
    }>;
    approveLesson(id: string, req: any): Promise<{
        subject: {
            grade: number | null;
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string | null;
            isActive: boolean;
            description: string | null;
            credits: number | null;
            colorCode: string | null;
        } | null;
        teacher: {
            id: string;
            name: string;
            email: string | null;
        } | null;
    } & {
        grade: number | null;
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        status: import("@prisma/client").$Enums.LessonStatus;
        title: string;
        type: import("@prisma/client").$Enums.ContentType;
        description: string | null;
        isLocked: boolean;
        subjectId: string | null;
        teacherId: string | null;
        periodNumber: number | null;
        maxMarks: number | null;
        dueDate: Date | null;
        createdById: string | null;
        attachments: string | null;
        instructions: string | null;
        objective: string | null;
        lessonContent: string | null;
        stream: string | null;
        semesterId: string | null;
        lessonDate: Date | null;
        totalPoints: number | null;
        unitNumber: number | null;
        topicName: string | null;
        topicId: string | null;
        competency: string | null;
        syllabusMappingId: string | null;
        isExamPrep: boolean;
        sectionName: string | null;
        reviewedBy: string | null;
        reviewedAt: Date | null;
    }>;
    rejectLesson(id: string, reason: string, req: any): Promise<{
        subject: {
            grade: number | null;
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string | null;
            isActive: boolean;
            description: string | null;
            credits: number | null;
            colorCode: string | null;
        } | null;
        teacher: {
            id: string;
            name: string;
            email: string | null;
        } | null;
    } & {
        grade: number | null;
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        status: import("@prisma/client").$Enums.LessonStatus;
        title: string;
        type: import("@prisma/client").$Enums.ContentType;
        description: string | null;
        isLocked: boolean;
        subjectId: string | null;
        teacherId: string | null;
        periodNumber: number | null;
        maxMarks: number | null;
        dueDate: Date | null;
        createdById: string | null;
        attachments: string | null;
        instructions: string | null;
        objective: string | null;
        lessonContent: string | null;
        stream: string | null;
        semesterId: string | null;
        lessonDate: Date | null;
        totalPoints: number | null;
        unitNumber: number | null;
        topicName: string | null;
        topicId: string | null;
        competency: string | null;
        syllabusMappingId: string | null;
        isExamPrep: boolean;
        sectionName: string | null;
        reviewedBy: string | null;
        reviewedAt: Date | null;
    }>;
    getPendingReview(req: any, departmentId?: string): Promise<({
        academicYear: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            isActive: boolean;
            startDate: Date;
            endDate: Date;
            ethiopianYear: number | null;
            curriculumType: import("@prisma/client").$Enums.CurriculumType;
            calendarType: import("@prisma/client").$Enums.CalendarType;
        } | null;
        subject: {
            grade: number | null;
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string | null;
            isActive: boolean;
            description: string | null;
            credits: number | null;
            colorCode: string | null;
        } | null;
        teacher: {
            id: string;
            name: string;
            email: string | null;
        } | null;
    } & {
        grade: number | null;
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        status: import("@prisma/client").$Enums.LessonStatus;
        title: string;
        type: import("@prisma/client").$Enums.ContentType;
        description: string | null;
        isLocked: boolean;
        subjectId: string | null;
        teacherId: string | null;
        periodNumber: number | null;
        maxMarks: number | null;
        dueDate: Date | null;
        createdById: string | null;
        attachments: string | null;
        instructions: string | null;
        objective: string | null;
        lessonContent: string | null;
        stream: string | null;
        semesterId: string | null;
        lessonDate: Date | null;
        totalPoints: number | null;
        unitNumber: number | null;
        topicName: string | null;
        topicId: string | null;
        competency: string | null;
        syllabusMappingId: string | null;
        isExamPrep: boolean;
        sectionName: string | null;
        reviewedBy: string | null;
        reviewedAt: Date | null;
    })[]>;
    submitHomework(homeworkId: string, submitHomeworkDto: SubmitHomeworkDto, req: any): Promise<any>;
    gradeHomework(submissionId: string, gradeHomeworkDto: GradeHomeworkDto, req: any): Promise<any>;
    getCoverageReport(query: LessonCoverageQueryDto, req: any): Promise<{
        summary: {
            totalUnits: any;
            coveredUnits: any;
            coveragePercentage: number;
            totalLessons: number;
        };
        coverageByUnit: any;
    }>;
    getLessonWithLock(id: string, req: any): Promise<{
        resources: never[];
        homework: {
            description: string;
            id: string;
            title: string;
        } | null;
        isLocked: boolean;
        lockMessage: string;
        subject: {
            grade: number | null;
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string | null;
            isActive: boolean;
            description: string | null;
            credits: number | null;
            colorCode: string | null;
        } | null;
        teacher: {
            id: string;
            name: string;
        } | null;
        attachmentsNew: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            fileUrl: string;
            fileName: string;
            fileSize: number | null;
            contentId: string;
            fileType: string | null;
            uploadedBy: string;
        }[];
        grade: number | null;
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        status: import("@prisma/client").$Enums.LessonStatus;
        title: string;
        type: import("@prisma/client").$Enums.ContentType;
        description: string | null;
        subjectId: string | null;
        teacherId: string | null;
        periodNumber: number | null;
        maxMarks: number | null;
        dueDate: Date | null;
        createdById: string | null;
        attachments: string | null;
        instructions: string | null;
        objective: string | null;
        lessonContent: string | null;
        stream: string | null;
        semesterId: string | null;
        lessonDate: Date | null;
        totalPoints: number | null;
        unitNumber: number | null;
        topicName: string | null;
        topicId: string | null;
        competency: string | null;
        syllabusMappingId: string | null;
        isExamPrep: boolean;
        sectionName: string | null;
        reviewedBy: string | null;
        reviewedAt: Date | null;
    } | {
        homework: {
            id: string;
            title: string;
            description: string;
        } | null;
        submission: null;
        isLocked: boolean;
        subject: {
            grade: number | null;
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string | null;
            isActive: boolean;
            description: string | null;
            credits: number | null;
            colorCode: string | null;
        } | null;
        teacher: {
            id: string;
            name: string;
        } | null;
        resources: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            title: string;
            description: string | null;
            isLocked: boolean;
            resourceType: import("@prisma/client").$Enums.ResourceType;
            fileUrl: string;
            fileName: string;
            fileSize: number | null;
            mimeType: string | null;
            contentId: string;
            uploadedBy: string;
        }[];
        attachmentsNew: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            fileUrl: string;
            fileName: string;
            fileSize: number | null;
            contentId: string;
            fileType: string | null;
            uploadedBy: string;
        }[];
        grade: number | null;
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        status: import("@prisma/client").$Enums.LessonStatus;
        title: string;
        type: import("@prisma/client").$Enums.ContentType;
        description: string | null;
        subjectId: string | null;
        teacherId: string | null;
        periodNumber: number | null;
        maxMarks: number | null;
        dueDate: Date | null;
        createdById: string | null;
        attachments: string | null;
        instructions: string | null;
        objective: string | null;
        lessonContent: string | null;
        stream: string | null;
        semesterId: string | null;
        lessonDate: Date | null;
        totalPoints: number | null;
        unitNumber: number | null;
        topicName: string | null;
        topicId: string | null;
        competency: string | null;
        syllabusMappingId: string | null;
        isExamPrep: boolean;
        sectionName: string | null;
        reviewedBy: string | null;
        reviewedAt: Date | null;
    }>;
    findAll(query: LessonQueryDto, req: any): Promise<{
        data: {
            section: string | null;
            homework: {
                id: string;
                title: string;
                description: string;
            } | null;
            academicYear: {
                id: string;
                schoolId: string;
                createdAt: Date;
                updatedAt: Date;
                name: string;
                isActive: boolean;
                startDate: Date;
                endDate: Date;
                ethiopianYear: number | null;
                curriculumType: import("@prisma/client").$Enums.CurriculumType;
                calendarType: import("@prisma/client").$Enums.CalendarType;
            } | null;
            subject: {
                grade: number | null;
                id: string;
                schoolId: string;
                createdAt: Date;
                updatedAt: Date;
                name: string;
                code: string | null;
                isActive: boolean;
                description: string | null;
                credits: number | null;
                colorCode: string | null;
            } | null;
            teacher: {
                id: string;
                name: string;
                email: string | null;
            } | null;
            semester: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                name: string;
                academicYearId: string;
                startDate: Date;
                endDate: Date;
                order: number;
                isLocked: boolean;
                percentageWeight: number;
            } | null;
            attachmentsNew: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                fileUrl: string;
                fileName: string;
                fileSize: number | null;
                contentId: string;
                fileType: string | null;
                uploadedBy: string;
            }[];
            grade: number | null;
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            classId: string | null;
            sectionId: string | null;
            academicYearId: string | null;
            status: import("@prisma/client").$Enums.LessonStatus;
            title: string;
            type: import("@prisma/client").$Enums.ContentType;
            description: string | null;
            isLocked: boolean;
            subjectId: string | null;
            teacherId: string | null;
            periodNumber: number | null;
            maxMarks: number | null;
            dueDate: Date | null;
            createdById: string | null;
            attachments: string | null;
            instructions: string | null;
            objective: string | null;
            lessonContent: string | null;
            stream: string | null;
            semesterId: string | null;
            lessonDate: Date | null;
            totalPoints: number | null;
            unitNumber: number | null;
            topicName: string | null;
            topicId: string | null;
            competency: string | null;
            syllabusMappingId: string | null;
            isExamPrep: boolean;
            sectionName: string | null;
            reviewedBy: string | null;
            reviewedAt: Date | null;
        }[];
        meta: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
    }>;
    getFormData(req: any): Promise<{
        academicYears: never[];
        activeAcademicYearId: null;
        terms: never[];
        grades: never[];
        sectionsByGrade: {};
        allSubjects: never[];
        teacherSubjects: never[];
        periods: {
            value: number;
            label: string;
        }[];
    } | {
        academicYears: {
            id: string;
            name: string;
            isActive: boolean;
        }[];
        activeAcademicYearId: string;
        terms: {
            id: string;
            name: string;
            startDate: string;
            endDate: string;
        }[];
        grades: (number | null)[];
        sectionsByGrade: Record<number, {
            id: string;
            name: string;
            classId: string;
        }[]>;
        allSubjects: {
            id: string;
            name: string;
            code?: string;
            grade: number;
            section: string;
        }[];
        teacherSubjects: {
            id: string;
            name: string;
            code?: string;
            grade: number;
            section: string;
        }[];
        periods: {
            value: number;
            label: string;
        }[];
    }>;
    findOne(id: string, req: any): Promise<{
        section: string | null;
        homework: {
            id: string;
            title: string;
            description: string;
        } | null;
        academicYear: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            isActive: boolean;
            startDate: Date;
            endDate: Date;
            ethiopianYear: number | null;
            curriculumType: import("@prisma/client").$Enums.CurriculumType;
            calendarType: import("@prisma/client").$Enums.CalendarType;
        } | null;
        subject: {
            grade: number | null;
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string | null;
            isActive: boolean;
            description: string | null;
            credits: number | null;
            colorCode: string | null;
        } | null;
        teacher: {
            id: string;
            name: string;
            email: string | null;
        } | null;
        semester: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            academicYearId: string;
            startDate: Date;
            endDate: Date;
            order: number;
            isLocked: boolean;
            percentageWeight: number;
        } | null;
        attachmentsNew: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            fileUrl: string;
            fileName: string;
            fileSize: number | null;
            contentId: string;
            fileType: string | null;
            uploadedBy: string;
        }[];
        grade: number | null;
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        status: import("@prisma/client").$Enums.LessonStatus;
        title: string;
        type: import("@prisma/client").$Enums.ContentType;
        description: string | null;
        isLocked: boolean;
        subjectId: string | null;
        teacherId: string | null;
        periodNumber: number | null;
        maxMarks: number | null;
        dueDate: Date | null;
        createdById: string | null;
        attachments: string | null;
        instructions: string | null;
        objective: string | null;
        lessonContent: string | null;
        stream: string | null;
        semesterId: string | null;
        lessonDate: Date | null;
        totalPoints: number | null;
        unitNumber: number | null;
        topicName: string | null;
        topicId: string | null;
        competency: string | null;
        syllabusMappingId: string | null;
        isExamPrep: boolean;
        sectionName: string | null;
        reviewedBy: string | null;
        reviewedAt: Date | null;
    }>;
    update(id: string, updateLessonDto: UpdateLessonDto, req: any): Promise<{
        academicYear: {
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            isActive: boolean;
            startDate: Date;
            endDate: Date;
            ethiopianYear: number | null;
            curriculumType: import("@prisma/client").$Enums.CurriculumType;
            calendarType: import("@prisma/client").$Enums.CalendarType;
        } | null;
        subject: {
            grade: number | null;
            id: string;
            schoolId: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            code: string | null;
            isActive: boolean;
            description: string | null;
            credits: number | null;
            colorCode: string | null;
        } | null;
        teacher: {
            id: string;
            name: string;
            email: string | null;
        } | null;
        semester: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            name: string;
            academicYearId: string;
            startDate: Date;
            endDate: Date;
            order: number;
            isLocked: boolean;
            percentageWeight: number;
        } | null;
        attachmentsNew: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            fileUrl: string;
            fileName: string;
            fileSize: number | null;
            contentId: string;
            fileType: string | null;
            uploadedBy: string;
        }[];
    } & {
        grade: number | null;
        id: string;
        schoolId: string;
        createdAt: Date;
        updatedAt: Date;
        classId: string | null;
        sectionId: string | null;
        academicYearId: string | null;
        status: import("@prisma/client").$Enums.LessonStatus;
        title: string;
        type: import("@prisma/client").$Enums.ContentType;
        description: string | null;
        isLocked: boolean;
        subjectId: string | null;
        teacherId: string | null;
        periodNumber: number | null;
        maxMarks: number | null;
        dueDate: Date | null;
        createdById: string | null;
        attachments: string | null;
        instructions: string | null;
        objective: string | null;
        lessonContent: string | null;
        stream: string | null;
        semesterId: string | null;
        lessonDate: Date | null;
        totalPoints: number | null;
        unitNumber: number | null;
        topicName: string | null;
        topicId: string | null;
        competency: string | null;
        syllabusMappingId: string | null;
        isExamPrep: boolean;
        sectionName: string | null;
        reviewedBy: string | null;
        reviewedAt: Date | null;
    }>;
    delete(id: string, req: any): Promise<{
        message: string;
    }>;
}
