"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useQueryClient } from "@tanstack/react-query";
import { queryKeys } from "@/lib/query-keys";
import { toast } from "sonner";
import {
  AlertCircle,
  CheckCircle2,
  CreditCard,
  Download,
  FileSpreadsheet,
  Loader2,
  ShieldCheck,
  Upload,
  UserPlus,
} from "lucide-react";

import { useTranslations } from "@/hooks/useTranslations";
import {
  academicYearsAPI,
  classesAPI,
  sectionsAPI,
  studentsAPI,
} from "@/lib/api";
import { credentialsAPI, CredentialResult } from "@/lib/api/admin";
import { bulkUploadAPI, BulkUploadResult } from "@/lib/api/bulk-upload";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

type UploadType = "staff" | "students-auto";
type CreateType = "student" | "staff";

type PendingCredential = {
  id: string;
  name: string;
  email: string;
  username: string;
  temporaryPassword: string;
  role: string;
  isSent: boolean;
  sentAt: string | null;
  sentVia: string | null;
  createdAt: string;
  expiresAt: string;
};

type CreatedCredential = CredentialResult & {
  wasAutoGenerated?: boolean;
};

type StudentOption = {
  userId: string;
  studentProfileId: string;
  name: string;
  studentCode?: string;
  className?: string;
  section?: string;
};

const ROLE_COLORS: Record<string, string> = {
  TEACHER: "text-violet-600 bg-violet-50 border-violet-200 dark:text-violet-300 dark:bg-violet-950/30 dark:border-violet-900",
  STUDENT: "text-sky-600 bg-sky-50 border-sky-200 dark:text-sky-300 dark:bg-sky-950/30 dark:border-sky-900",
  PARENT: "text-emerald-600 bg-emerald-50 border-emerald-200 dark:text-emerald-300 dark:bg-emerald-950/30 dark:border-emerald-900",
  ADMIN: "text-orange-600 bg-orange-50 border-orange-200 dark:text-orange-300 dark:bg-orange-950/30 dark:border-orange-900",
  REGISTRAR: "text-amber-600 bg-amber-50 border-amber-200 dark:text-amber-300 dark:bg-amber-950/30 dark:border-amber-900",
  FINANCE: "text-rose-600 bg-rose-50 border-rose-200 dark:text-rose-300 dark:bg-rose-950/30 dark:border-rose-900",
};

function getUploadSummary(result: BulkUploadResult | null) {
  if (!result) {
    return { totalRecords: 0, successfulCount: 0, failedCount: 0, skippedCount: 0 };
  }

  if (result.summary) {
    return result.summary;
  }

  return {
    totalRecords: result.totalRecords || 0,
    successfulCount: result.successfulCount || 0,
    failedCount: result.failedCount || 0,
    skippedCount: result.skippedCount || result.skippedRecords?.length || 0,
  };
}

function normalizeStudentsResponse(raw: any): StudentOption[] {
  const list = raw?.data || raw || [];
  return (Array.isArray(list) ? list : []).map((student: any) => ({
    userId: student.userId || student.id,
    studentProfileId: student.id || student.studentProfile?.id,
    name: student.user?.name || student.name || "Unnamed Student",
    studentCode: student.studentCode || student.studentProfile?.studentCode,
    className: student.className || student.studentProfile?.className,
    section: student.section || student.studentProfile?.section,
  })).filter((student: StudentOption) => student.studentProfileId);
}

function normalizeCreatedCredentials(response: any, type: CreateType): CreatedCredential[] {
  if (type === "student") {
    return response?.students || response?.credentials || [];
  }

  if (type === "staff") {
    return response?.staff || response?.credentials || [];
  }

  const parent = response?.parent || response;
  const email = parent?.email || response?.email || "";
  const username = parent?.username || response?.username;
  const temporaryPassword = response?.temporaryPassword || response?.tempPassword;

  if (!username || !temporaryPassword) {
    return [];
  }

  return [{
    name: parent?.name || response?.name || "Parent",
    email,
    username,
    temporaryPassword,
    role: "PARENT",
  }];
}

function downloadBlob(data: BlobPart, filename: string) {
  const url = window.URL.createObjectURL(new Blob([data]));
  const link = document.createElement("a");
  link.href = url;
  link.setAttribute("download", filename);
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.URL.revokeObjectURL(url);
}

function normalizeStudentAndParentNames(fullName?: string, explicitParentName?: string) {
  const normalizedStudentName = String(fullName || "").replace(/\s+/g, " ").trim();
  const normalizedExplicitParentName = explicitParentName?.replace(/\s+/g, " ").trim() || "";

  if (!normalizedStudentName) {
    return { studentName: "", parentName: normalizedExplicitParentName };
  }

  if (normalizedExplicitParentName) {
    return { studentName: normalizedStudentName, parentName: normalizedExplicitParentName };
  }

  const nameParts = normalizedStudentName.split(" ").filter(Boolean);
  if (nameParts.length >= 3) {
    return {
      studentName: nameParts.slice(0, 2).join(" "),
      parentName: nameParts.slice(1).join(" "),
    };
  }

  if (nameParts.length === 2) {
    // When there's no explicit parent_name, don't derive parent from a 2-part name
    // (e.g., "John Bekele" - Bekele is just the last name, not a parent)
    if (!normalizedExplicitParentName) {
      return { studentName: normalizedStudentName };
    }
    return {
      studentName: normalizedStudentName,
      parentName: nameParts[1],
    };
  }

  return { studentName: normalizedStudentName, parentName: "" };
}

export default function BulkUploadPage() {
  const { t } = useTranslations<any>("bulkUpload");
  const router = useRouter();
  const queryClient = useQueryClient();
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [activeTab, setActiveTab] = useState("import");
  const [uploadType, setUploadType] = useState<UploadType>("staff");
  const [createType, setCreateType] = useState<CreateType>("student");
  const [academicYears, setAcademicYears] = useState<any[]>([]);
  const [selectedYear, setSelectedYear] = useState("");
  const [classes, setClasses] = useState<any[]>([]);
  const [sections, setSections] = useState<any[]>([]);
  const [students, setStudents] = useState<StudentOption[]>([]);

  const [isLoadingSetup, setIsLoadingSetup] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const [isCreating, setIsCreating] = useState(false);
  const [isLoadingCreds, setIsLoadingCreds] = useState(false);
  const [isDragging, setIsDragging] = useState(false);

  const [importFile, setImportFile] = useState<File | null>(null);
  const [previewData, setPreviewData] = useState<any[]>([]);
  const [uploadResult, setUploadResult] = useState<BulkUploadResult | null>(null);
  const [validationWarnings, setValidationWarnings] = useState<string[]>([]);

  const [createdCredentials, setCreatedCredentials] = useState<CreatedCredential[]>([]);
  const [createdMessage, setCreatedMessage] = useState("");

  const [studentForm, setStudentForm] = useState({
    name: "",
    email: "",
    phone: "",
    classId: "",
  });
  const [staffForm, setStaffForm] = useState({
    name: "",
    email: "",
    phone: "",
    role: "TEACHER" as "TEACHER" | "ADMIN" | "IT_MANAGER" | "REGISTRAR" | "FINANCE",
  });

  useEffect(() => {
    void initializePage();
  }, []);

  useEffect(() => {
    if (selectedYear) {
      void fetchClasses(selectedYear);
    }
  }, [selectedYear]);

  useEffect(() => {
    if (studentForm.classId) {
      void fetchSections(studentForm.classId);
      return;
    }

    setSections([]);

  }, [studentForm.classId]);

  async function initializePage() {
    setIsLoadingSetup(true);
    try {
      const [yearsResponse, studentsResponse] = await Promise.all([
        academicYearsAPI.getAll(),
        studentsAPI.getAll({ status: "APPROVED", limit: "200" }),
      ]);

      const yearList = yearsResponse.data || [];
      setAcademicYears(yearList);

      const activeYear = yearList.find((year: any) => year.isActive);
      if (activeYear) {
        setSelectedYear(activeYear.id);
        await fetchClasses(activeYear.id);
      }

      setStudents(normalizeStudentsResponse(studentsResponse.data));
    } catch (error) {
      console.error("Failed to initialize bulk user page", error);
      toast.error(t.errors.initFailed);
    } finally {
      setIsLoadingSetup(false);
    }
  }

  async function fetchClasses(academicYearId: string) {
    try {
      const response = await classesAPI.getAll({ academicYearId });
      setClasses(response.data || []);
    } catch (error) {
      console.error("Failed to fetch classes", error);
      setClasses([]);
    }
  }

  async function fetchSections(classId: string) {
    try {
      const response = await sectionsAPI.getAll({ classId });
      setSections(response.data || []);
    } catch (error) {
      console.error("Failed to fetch sections", error);
      setSections([]);
    }
  }

  async function processFile(file: File) {
    setImportFile(file);
    setUploadResult(null);
    setValidationWarnings([]);
    const text = await file.text();
    const rows = text.split("\n").filter((row) => row.trim());
    if (rows.length === 0) {
      setPreviewData([]);
      return;
    }

    const headers = rows[0].split(",").map(h => h.trim()).filter(h => h && h.toLowerCase() !== '#');
    const warnings: string[] = [];
    
    const normalizedHeaders = headers.map(h => h.toLowerCase().replace(/\s+/g, '_'));
    const hasStaffFields = normalizedHeaders.some(h => ['full_name', 'name', 'email', 'phone', 'role'].includes(h));
    const hasStudentFields = normalizedHeaders.some(h => ['first_name', 'middle_name', 'last_name', 'current_class', 'parent_name', 'parent_phone', 'gender'].includes(h));
    
    if (uploadType === 'staff' && hasStudentFields) {
      warnings.push("STUDENT_DATA_DETECTED");
    } else if (uploadType === 'students-auto' && hasStaffFields && !hasStudentFields) {
      warnings.push("STAFF_DATA_DETECTED");
    }

    const parsed = rows.slice(1).map((row) => {
      // Handle row - may have newlines/tabs within it from Excel format
      let cleanRow = row.replace(/\n/g, ' ').replace(/\t/g, ' ');
      // Collapse multiple spaces
      cleanRow = cleanRow.replace(/\s+/g, ' ').trim();
      
      let values = cleanRow.split(",").map(v => v.trim());
      // Remove leading row numbers (1, 2, 3...) - check if first value is purely numeric and remove it
      if (values.length > 0 && /^\d+$/.test(values[0])) {
        values = values.slice(1);
      }
      // Also remove empty leading values that might come from extra columns
      while (values.length > 0 && values[0] === '') {
        values = values.slice(1);
      }
      // If we have more values than headers, check if first few are single letters (likely garbage)
      while (values.length > headers.length && /^[A-Za-z]$/.test(values[0])) {
        values = values.slice(1);
      }
      const record: Record<string, string> = {};
      headers.forEach((header, index) => {
        record[header] = values[index] || "";
      });

      const studentNameKey = headers.find((header) => {
        const normalized = header.trim().toLowerCase();
        return normalized === "full_name" || normalized === "fullname" || normalized === "name" || normalized === "student_name";
      })?.trim();
      const parentNameKey = headers.find((header) => {
        const normalized = header.trim().toLowerCase();
        return normalized === "parent_name" || normalized === "parent_fullname" || normalized === "guardian_name" || normalized === "parent";
      })?.trim();

      if (studentNameKey) {
        const normalizedNames = normalizeStudentAndParentNames(
          record[studentNameKey],
          parentNameKey ? record[parentNameKey] : "",
        );
        record[studentNameKey] = normalizedNames.studentName;
        if (parentNameKey && normalizedNames.parentName) {
          record[parentNameKey] = normalizedNames.parentName;
        } else if (!parentNameKey && normalizedNames.parentName) {
          record.parent_name = normalizedNames.parentName;
        }
      }

      return record;
    });
    setPreviewData(parsed);
    setValidationWarnings(warnings);
  }

  async function handleUpload() {
    if (!importFile) {
      toast.error(t.errors.selectFile);
      return;
    }

    // Check for data type mismatch warnings
    if (validationWarnings.length > 0) {
      const isStaffUpload = uploadType === 'staff';
      const hasStudentWarning = validationWarnings.includes('STUDENT_DATA_DETECTED');
      const hasStaffWarning = validationWarnings.includes('STAFF_DATA_DETECTED');

      if (isStaffUpload && hasStudentWarning) {
        toast.error(t.errors.uploadStaffAsStudent);
        return;
      } else if (!isStaffUpload && hasStaffWarning) {
        toast.error(t.errors.uploadStudentAsStaff);
        return;
      }
    }

    setIsUploading(true);
    try {
      const response =
        uploadType === "staff"
          ? await bulkUploadAPI.uploadStaff(importFile, selectedYear || undefined)
          : await bulkUploadAPI.uploadStudentsAuto(importFile, selectedYear || undefined);

      setUploadResult(response.data);
      setCreatedCredentials([]);
      setCreatedMessage("");
      if (response.data.status === "success") {
        toast.success(t.messages.importSuccess);
      } else if (response.data.status === "partial") {
        toast.warning(t.messages.importPartial);
      } else {
        toast.error(response.data.message || t.errors.importFailed);
      }
      if (response.data.status === "success" || response.data.status === "partial") {
        queryClient.invalidateQueries({ queryKey: queryKeys.users.all });
        queryClient.invalidateQueries({ queryKey: queryKeys.students.all });
      }
    } catch (error: any) {
      toast.error(error.response?.data?.message || t.errors.importProcessFailed);
    } finally {
      setIsUploading(false);
    }
  }

  async function handleCreateOne() {
    setIsCreating(true);
    try {
      let response: any;

      if (createType === "student") {
        if (!studentForm.name.trim()) {
          toast.error(t.errors.studentNameRequired);
          return;
        }

        if (!studentForm.phone.trim()) {
          toast.error(t.errors.studentPhoneRequired);
          return;
        }

        response = await credentialsAPI.createStudent({
          academicYear: selectedYear || undefined,
          students: [{
            name: studentForm.name.trim(),
            email: studentForm.email.trim() || undefined,
            phone: studentForm.phone.trim() || undefined,
            classId: studentForm.classId || undefined,
            generateCredentials: true,
          }],
        });
      } else if (createType === "staff") {
        if (!staffForm.name.trim() || !staffForm.email.trim()) {
          toast.error(t.errors.staffNameEmailRequired);
          return;
        }

        response = await credentialsAPI.createStaff({
          academicYear: selectedYear || undefined,
          staff: [{
            name: staffForm.name.trim(),
            email: staffForm.email.trim(),
            phone: staffForm.phone.trim() || undefined,
            role: staffForm.role,
            generateCredentials: true,
          }],
        });
      }

      const normalized = normalizeCreatedCredentials(response.data, createType);
      setCreatedCredentials(normalized);
      setCreatedMessage(response.data?.message || t.messages.userCreated);
      setUploadResult(null);

      if (createType === "student") {
        setStudentForm({ name: "", email: "", phone: "", classId: "" });
        const studentsResponse = await studentsAPI.getAll({ status: "APPROVED", limit: "200" });
        setStudents(normalizeStudentsResponse(studentsResponse.data));
      } else if (createType === "staff") {
        setStaffForm({ name: "", email: "", phone: "", role: "TEACHER" });
      }

      toast.success(t.messages.userCreated);
      queryClient.invalidateQueries({ queryKey: queryKeys.users.all });
      queryClient.invalidateQueries({ queryKey: queryKeys.students.all });
    } catch (error: any) {
      toast.error(error.response?.data?.message || t.errors.createFailed);
    } finally {
      setIsCreating(false);
    }
  }

  async function downloadTemplate() {
    try {
      const response = await bulkUploadAPI.getTemplate(uploadType);
      downloadBlob(response.data, `template_${uploadType}.csv`);
    } catch (error) {
      toast.error(t.errors.downloadTemplate);
    }
  }

  async function exportCreatedCredentials() {
    if (createdCredentials.length === 0) {
      return;
    }

    try {
      const response = await credentialsAPI.exportToCSV(createdCredentials);
      downloadBlob(response.data, `created_credentials_${Date.now()}.csv`);
    } catch (error) {
      toast.error(t.errors.exportFailed);
    }
  }

  async function downloadImportReport() {
    if (!uploadResult?.credentials?.length) {
      return;
    }

    try {
      const response = await bulkUploadAPI.generateReport(
        uploadResult.credentials.map((credential) => ({
          name: credential.name,
          email: credential.email,
          username: credential.username,
          temporaryPassword: credential.temporaryPassword || "",
          role: credential.role,
        })),
      );
      downloadBlob(response.data, `bulk_credentials_${Date.now()}.csv`);
    } catch (error) {
      toast.error(t.errors.downloadReportFailed);
    }
  }

  const uploadSummary = getUploadSummary(uploadResult);
  const successRate = uploadSummary.totalRecords
    ? Math.round((uploadSummary.successfulCount / uploadSummary.totalRecords) * 100)
    : 0;

  return (
    <div className="w-full px-4 py-6 sm:px-6">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white">
          {t.title}
        </h1>
        <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
          {t.description}
        </p>
      </div>

      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="inline-flex h-auto w-max min-w-0 flex-nowrap bg-transparent p-0 shadow-none border-0">
          <TabsTrigger value="import" className="shrink-0 gap-1.5 px-3 text-xs font-semibold data-[state=active]:bg-transparent data-[state=active]:shadow-none border-b-2 border-transparent data-[state=active]:border-[var(--brand-color,#e35336)] data-[state=active]:text-[var(--brand-color,#e35336)] rounded-none md:gap-2 md:px-4 md:text-sm">
            {t.tabs.import}
          </TabsTrigger>
          <TabsTrigger value="create" className="shrink-0 gap-1.5 px-3 text-xs font-semibold data-[state=active]:bg-transparent data-[state=active]:shadow-none border-b-2 border-transparent data-[state=active]:border-[var(--brand-color,#e35336)] data-[state=active]:text-[var(--brand-color,#e35336)] rounded-none md:gap-2 md:px-4 md:text-sm">
            {t.tabs.create}
          </TabsTrigger>
        </TabsList>

        <TabsContent value="import" className="space-y-6">
          <div className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex flex-wrap items-center gap-x-4 gap-y-3">
              <div className="flex items-center gap-2 rounded-lg bg-slate-100 p-1 dark:bg-slate-700">
                  {[
                    { id: "staff", label: t.uploadTypes.staff },
                    { id: "students-auto", label: t.uploadTypes.studentsAuto },
                  ].map((item) => (
                  <button
                    key={item.id}
                    type="button"
                    onClick={() => setUploadType(item.id as UploadType)}
                    className={`rounded-md px-3 py-1.5 text-sm font-medium transition ${
                      uploadType === item.id
                        ? "bg-white text-slate-900 shadow-sm dark:bg-slate-600 dark:text-white"
                        : "text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200"
                    }`}
                  >
                    {item.label}
                  </button>
                ))}
              </div>
              <Select value={selectedYear} onValueChange={setSelectedYear}>
                <SelectTrigger className="h-9 w-48">
                  <SelectValue placeholder={t.academicYear} />
                </SelectTrigger>
                <SelectContent>
                  {academicYears.map((year) => (
                    <SelectItem key={year.id} value={year.id}>
                      {year.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <Button variant="outline" size="sm" onClick={downloadTemplate}>
              <Download className="mr-2 h-4 w-4" />
              {t.template}
            </Button>
          </div>

          {!uploadResult ? (
            <>
              <div
                className={`flex cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed p-12 transition ${
                  isDragging
                    ? "border-[var(--brand-color)] bg-[color:rgba(var(--brand-color-rgb),0.06)]"
                    : importFile
                    ? "border-emerald-300 bg-emerald-50/50 dark:border-emerald-700 dark:bg-emerald-900/10"
                    : "border-slate-300 bg-white hover:border-slate-400 dark:border-slate-600 dark:bg-slate-800 dark:hover:border-slate-500"
                }`}
                onDragOver={(event) => {
                  event.preventDefault();
                  setIsDragging(true);
                }}
                onDragLeave={() => setIsDragging(false)}
                onDrop={(event) => {
                  event.preventDefault();
                  setIsDragging(false);
                  const file = event.dataTransfer.files?.[0];
                  if (file?.name.endsWith(".csv")) {
                    void processFile(file);
                  } else {
                    toast.error(t.dropCsv);
                  }
                }}
                onClick={() => !importFile && fileInputRef.current?.click()}
              >
                <input
                  ref={fileInputRef}
                  type="file"
                  accept=".csv"
                  className="hidden"
                  onChange={(event) => {
                    const file = event.target.files?.[0];
                    if (file) {
                      void processFile(file);
                    }
                  }}
                />
                {importFile ? (
                  <>
                    <div className="mb-3 flex h-14 w-14 items-center justify-center rounded-full bg-emerald-100 dark:bg-emerald-900/40">
                      <CheckCircle2 className="h-7 w-7 text-emerald-600 dark:text-emerald-400" />
                    </div>
                    <p className="text-lg font-semibold text-slate-900 dark:text-white">{importFile.name}</p>
                    <p className="mt-1 text-sm text-slate-500">{(importFile.size / 1024).toFixed(1)} KB &middot; {t.csvReady}</p>
                    <div className="mt-4 flex gap-3">
                      <Button size="sm" onClick={(e) => { e.stopPropagation(); handleUpload(); }} disabled={isUploading}>
                        {isUploading ? (
                          <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> {t.importing}</>
                        ) : (
                          <><Upload className="mr-2 h-4 w-4" /> {t.startImport}</>
                        )}
                      </Button>
                      <Button size="sm" variant="outline" onClick={(e) => { e.stopPropagation(); setImportFile(null); setPreviewData([]); }}>
                        {t.remove}
                      </Button>
                    </div>
                  </>
                ) : (
                  <>
                    <div className="mb-3 flex h-14 w-14 items-center justify-center rounded-full bg-slate-100 dark:bg-slate-700">
                      <FileSpreadsheet className="h-7 w-7 text-slate-500 dark:text-slate-400" />
                    </div>
                    <p className="text-lg font-semibold text-slate-900 dark:text-white">{t.dropHere}</p>
                    <p className="mt-1 text-sm text-slate-500">{t.csvOnly}</p>
                  </>
                )}
              </div>

              {previewData.length > 0 && (
                <div className="rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800">
                  <div className="flex items-center justify-between border-b border-slate-100 px-5 py-3 dark:border-slate-700">
                    <div>
                      <p className="text-sm font-semibold text-slate-900 dark:text-white">{t.preview}</p>
                      <p className="text-xs text-slate-500">{t.allRows.replace("{count}", String(previewData.length))}</p>
                    </div>
                  </div>
                  {validationWarnings.length > 0 && (
                    <div className="mx-5 mt-3 flex items-start gap-3 rounded-lg bg-amber-50 px-4 py-3 dark:bg-amber-950/30">
                      <AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-amber-600 dark:text-amber-400" />
                      <p className="text-sm text-amber-800 dark:text-amber-200">
                        {validationWarnings.includes('STUDENT_DATA_DETECTED')
                          ? t.warnings.studentDataAsStaff
                          : t.warnings.staffDataAsStudent}
                      </p>
                    </div>
                  )}
                  <div className="overflow-x-auto p-5">
                    <table className="w-full text-left text-sm">
                      <thead>
                        <tr className="border-b border-slate-200 dark:border-slate-700">
                          {Object.keys(previewData[0]).map((header) => (
                            <th key={header} className="whitespace-nowrap px-3 py-2 font-semibold text-slate-500">{header}</th>
                          ))}
                        </tr>
                      </thead>
                      <tbody>
                        {previewData.map((row, index) => (
                          <tr key={index} className="border-b border-slate-100 last:border-0 dark:border-slate-700">
                            {Object.entries(row).map(([key, value]) => (
                              <td key={`${index}-${key}`} className="whitespace-nowrap px-3 py-2 text-slate-700 dark:text-slate-300">
                                {String(value || "—")}
                              </td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
            </>
          ) : (
            <div className="space-y-5">
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="text-lg font-semibold text-slate-900 dark:text-white">{t.importResult}</h3>
                  <p className="text-sm text-slate-500">{uploadResult.message}</p>
                </div>
                <Button variant="outline" size="sm" onClick={() => setUploadResult(null)}>
                  {t.newImport}
                </Button>
              </div>

              <div className="grid gap-4 sm:grid-cols-5">
                <div className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800">
                  <p className="text-xs font-medium text-slate-500">{t.stats.total}</p>
                  <p className="mt-1 text-2xl font-bold text-slate-900 dark:text-white">{uploadSummary.totalRecords}</p>
                </div>
                <div className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800">
                  <p className="text-xs font-medium text-emerald-600">{t.stats.created}</p>
                  <p className="mt-1 text-2xl font-bold text-emerald-600">{uploadSummary.successfulCount}</p>
                </div>
                <div className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800">
                  <p className="text-xs font-medium text-red-500">{t.stats.failed}</p>
                  <p className="mt-1 text-2xl font-bold text-red-500">{uploadSummary.failedCount}</p>
                </div>
                <div className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800">
                  <p className="text-xs font-medium text-amber-600">Skipped</p>
                  <p className="mt-1 text-2xl font-bold text-amber-600">{uploadSummary.skippedCount}</p>
                </div>
                <div className="rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800">
                  <p className="text-xs font-medium text-slate-500">{t.stats.successRate}</p>
                  <div className="mt-2 flex items-center gap-2">
                    <div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-700">
                      <div className="h-full rounded-full bg-emerald-500 transition-all" style={{ width: `${successRate}%` }} />
                    </div>
                    <span className="text-sm font-bold text-slate-900 dark:text-white">{successRate}%</span>
                  </div>
                </div>
              </div>

              {uploadResult.credentials?.length ? (
                <div className="flex items-center justify-between rounded-xl border border-blue-200 bg-blue-50 px-5 py-4 dark:border-blue-800 dark:bg-blue-950/20">
                  <div className="flex items-start gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-600 text-white">
                      <ShieldCheck className="h-5 w-5" />
                    </div>
                    <div>
                      <p className="font-semibold text-slate-900 dark:text-white">{t.credentialsGenerated.replace("{count}", String(uploadResult.credentials.length))}</p>
                      <p className="text-sm text-slate-500">{t.exportHint}</p>
                    </div>
                  </div>
                  <Button size="sm" onClick={downloadImportReport}>
                    <Download className="mr-2 h-4 w-4" />
                    {t.export}
                  </Button>
                </div>
              ) : null}

              {uploadType === "students-auto" && uploadResult.credentials?.length ? (
                <div className="flex items-center justify-between rounded-xl border border-emerald-200 bg-emerald-50 px-5 py-4 dark:border-emerald-800 dark:bg-emerald-950/20">
                  <div className="flex items-start gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-emerald-600 text-white">
                      <CreditCard className="h-5 w-5" />
                    </div>
                    <div>
                      <p className="font-semibold text-slate-900 dark:text-white">{t.generateIdCards}</p>
                      <p className="text-sm text-slate-500">{t.forNewStudents.replace("{count}", String(uploadResult.credentials.length))}</p>
                    </div>
                  </div>
                  <Button
                    size="sm"
                    variant="outline"
                    className="border-emerald-300 text-emerald-700 hover:bg-emerald-100 dark:border-emerald-700 dark:text-emerald-400"
                    onClick={() => {
                      const ids = uploadResult.credentials?.map((c: any) => c.username).join(",");
                      router.push(`/admin/id-cards?studentIds=${ids || ""}`);
                    }}
                  >
                    <CreditCard className="mr-2 h-4 w-4" />
                    {t.generate}
                  </Button>
                </div>
              ) : null}

              {uploadResult.failedRecords?.length ? (
                <div className="rounded-xl border border-red-200 bg-white p-5 dark:border-red-800 dark:bg-slate-800">
                  <p className="mb-3 text-sm font-semibold text-red-600 dark:text-red-400">{t.failedRows.replace("{count}", String(uploadResult.failedRecords.length))}</p>
                  <div className="space-y-2">
                    {uploadResult.failedRecords.map((item: any, index: number) => (
                      <div key={index} className="rounded-lg border border-red-100 bg-red-50/50 px-4 py-3 dark:border-red-900 dark:bg-red-950/20">
                        <p className="text-sm font-medium text-slate-900 dark:text-white">
                          {item.record?.full_name || item.record?.email || `Row ${index + 1}`}
                        </p>
                        <p className="text-sm text-red-600 dark:text-red-400">{item.error}</p>
                      </div>
                    ))}
                  </div>
                </div>
              ) : null}

              {uploadResult.skippedRecords?.length ? (
                <div className="rounded-xl border border-amber-200 bg-white p-5 dark:border-amber-800 dark:bg-slate-800">
                  <p className="mb-3 text-sm font-semibold text-amber-600 dark:text-amber-400">
                    Skipped duplicate rows ({uploadResult.skippedRecords.length})
                  </p>
                  <div className="space-y-2">
                    {uploadResult.skippedRecords.map((item: any, index: number) => (
                      <div key={index} className="rounded-lg border border-amber-100 bg-amber-50/50 px-4 py-3 dark:border-amber-900 dark:bg-amber-950/20">
                        <p className="text-sm font-medium text-slate-900 dark:text-white">
                          {item.record?.full_name || item.record?.email || `Row ${index + 1}`}
                        </p>
                        <p className="text-sm text-amber-600 dark:text-amber-400">{item.reason}</p>
                      </div>
                    ))}
                  </div>
                </div>
              ) : null}
            </div>
          )}
        </TabsContent>

        <TabsContent value="create" className="space-y-5">
          <div className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-700 dark:bg-slate-800 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex flex-wrap items-center gap-x-4 gap-y-3">
              <div className="flex items-center gap-2 rounded-lg bg-slate-100 p-1 dark:bg-slate-700">
                  {[
                    { id: "student", label: t.createTypes.student },
                    { id: "staff", label: t.createTypes.staff },
                  ].map((item) => (
                  <button
                    key={item.id}
                    type="button"
                    onClick={() => setCreateType(item.id as CreateType)}
                    className={`rounded-md px-3 py-1.5 text-sm font-medium transition ${
                      createType === item.id
                        ? "bg-white text-slate-900 shadow-sm dark:bg-slate-600 dark:text-white"
                        : "text-slate-500 hover:text-slate-700 dark:text-slate-400 dark:hover:text-slate-200"
                    }`}
                  >
                    {item.label}
                  </button>
                ))}
              </div>
              <Select value={selectedYear} onValueChange={setSelectedYear}>
                <SelectTrigger className="h-9 w-48">
                  <SelectValue placeholder={t.academicYear} />
                </SelectTrigger>
                <SelectContent>
                  {academicYears.map((year) => (
                    <SelectItem key={year.id} value={year.id}>
                      {year.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <p className="text-xs text-slate-500">{t.autoStore}</p>
          </div>

          <div className="rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800">
            <div className="border-b border-slate-100 px-5 py-4 dark:border-slate-700">
              <h3 className="text-base font-semibold text-slate-900 dark:text-white">
                {createType === "student" ? t.createTitle.student : t.createTitle.staff}
              </h3>
            </div>
            <div className="p-5">
              {createType === "student" ? (
                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-600 dark:text-slate-400">{t.fullName}</Label>
                    <Input
                      value={studentForm.name}
                      onChange={(event) => setStudentForm((current) => ({ ...current, name: event.target.value }))}
                      placeholder={t.studentNamePlaceholder}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-600 dark:text-slate-400">{t.phone}</Label>
                    <Input
                      value={studentForm.phone}
                      onChange={(event) => setStudentForm((current) => ({ ...current, phone: event.target.value }))}
                      placeholder="0911000000"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-600 dark:text-slate-400">{t.email}</Label>
                    <Input
                      value={studentForm.email}
                      onChange={(event) => setStudentForm((current) => ({ ...current, email: event.target.value }))}
                      placeholder={t.emailPlaceholder}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-600 dark:text-slate-400">{t.class}</Label>
                    <Select
                      value={studentForm.classId}
                      onValueChange={(value) => setStudentForm((current) => ({ ...current, classId: value }))}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder={isLoadingSetup ? t.loadingClasses : t.optional} />
                      </SelectTrigger>
                      <SelectContent>
                        {classes.map((item: any) => (
                          <SelectItem key={item.id} value={item.id}>
                            {item.name}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              ) : (
                <div className="grid gap-4 sm:grid-cols-2">
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-600 dark:text-slate-400">{t.fullName}</Label>
                    <Input
                      value={staffForm.name}
                      onChange={(event) => setStaffForm((current) => ({ ...current, name: event.target.value }))}
                      placeholder={t.staffNamePlaceholder}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-600 dark:text-slate-400">{t.emailRequired}</Label>
                    <Input
                      value={staffForm.email}
                      onChange={(event) => setStaffForm((current) => ({ ...current, email: event.target.value }))}
                      placeholder={t.staffEmailPlaceholder}
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-600 dark:text-slate-400">{t.phone}</Label>
                    <Input
                      value={staffForm.phone}
                      onChange={(event) => setStaffForm((current) => ({ ...current, phone: event.target.value }))}
                      placeholder="0911000000"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs font-medium text-slate-600 dark:text-slate-400">{t.role}</Label>
                    <Select
                      value={staffForm.role}
                      onValueChange={(value: "TEACHER" | "ADMIN" | "IT_MANAGER" | "REGISTRAR" | "FINANCE") =>
                        setStaffForm((current) => ({ ...current, role: value }))
                      }
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="TEACHER">{t.roles.TEACHER}</SelectItem>
                        <SelectItem value="ADMIN">{t.roles.ADMIN}</SelectItem>
                        <SelectItem value="IT_MANAGER">{t.roles.IT_MANAGER}</SelectItem>
                        <SelectItem value="REGISTRAR">{t.roles.REGISTRAR}</SelectItem>
                        <SelectItem value="FINANCE">{t.roles.FINANCE}</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              )}

              <div className="mt-6 flex items-center justify-end gap-3 border-t border-slate-100 pt-4 dark:border-slate-700">
                <Button onClick={handleCreateOne} disabled={isCreating || isLoadingSetup}>
                  {isCreating ? (
                    <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> {t.creating}</>
                  ) : (
                    <><UserPlus className="mr-2 h-4 w-4" /> {t.createUser}</>
                  )}
                </Button>
              </div>
            </div>
          </div>

          {createdCredentials.length ? (
            <div className="rounded-xl border border-emerald-200 bg-emerald-50/70 dark:border-emerald-800 dark:bg-emerald-950/20">
              <div className="flex items-center justify-between border-b border-emerald-200 px-5 py-4 dark:border-emerald-800">
                <div>
                  <h3 className="text-base font-semibold text-emerald-700 dark:text-emerald-300">{t.credentialsReady}</h3>
                  <p className="text-sm text-slate-500">{createdMessage}</p>
                </div>
                <Button variant="outline" size="sm" onClick={exportCreatedCredentials}>
                  <Download className="mr-2 h-4 w-4" /> {t.exportCsv}
                </Button>
              </div>
              <div className="divide-y divide-emerald-200 dark:divide-emerald-800">
                {createdCredentials.map((credential, index) => (
                  <div key={`${credential.username}-${index}`} className="px-5 py-4">
                    <div className="flex items-start justify-between">
                      <div>
                        <p className="font-semibold text-slate-900 dark:text-white">{credential.name}</p>
                        <p className="text-sm text-slate-500">{credential.email || t.noEmail}</p>
                      </div>
                      <Badge className={ROLE_COLORS[credential.role] || ROLE_COLORS.STUDENT}>
                        {credential.role}
                      </Badge>
                    </div>
                    <div className="mt-3 grid gap-3 sm:grid-cols-2">
                      <div className="rounded-lg bg-slate-50 px-3 py-2 dark:bg-slate-900">
                        <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t.username}</p>
                        <p className="font-mono text-sm text-slate-900 dark:text-white">{credential.username}</p>
                      </div>
                      <div className="rounded-lg bg-slate-50 px-3 py-2 dark:bg-slate-900">
                        <p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{t.tempPassword}</p>
                        <p className="font-mono text-sm text-slate-900 dark:text-white">{credential.temporaryPassword}</p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ) : null}
        </TabsContent>
      </Tabs>
    </div>
  );
}
